### PR TITLE
Fixed return_data parameter for a few functions

### PR DESCRIPTION
**Pull request by sayantan1410**
#### Describe the changes you've made - Added data to the return_data_dict dictionary

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by ngupta23** [comment]
@sayantan1410 Can you add some unit tests for the plots that return the data? You need to check that when `return_data` is set as True, you get a dictionary back with at least 1 key. Don't have to check the specifics of the keys for now.

**Comment by ngupta23** [comment]
@sayantan1410 Apart from the unit tests, the rest looks good to me. We can merge once you add the unit tests. Thanks!

**Comment by sayantan1410** [comment]
Sure, will try to do it !! @ngupta23

**Comment by ngupta23** [comment]
Thanks @sayantan1410. I will merge it for now but modularize the unit tests after the merge. I will let you know once that is done.

**Comment by ngupta23** [comment]
Another quick suggestion. Please install `black` to autoformat the code before the PR. Thanks!

**Comment by sayantan1410** [comment]
Sorry missed the conversation here, Thank you for merging the PR, how can I modularize the unit test ? Also I will install black as well. @ngupta23

**Pull request merged**
