### PR TITLE
Preprocess time series

### PR DESCRIPTION
**Pull request by ngupta23**
## Related Issue or bug

Initial alignment of time series code with new preprocessing code. All time series tests pass locally now.

#### Describe the changes you've made

Several changes to make time-series module compatible with the new preprocessing flow.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Time Series unit tests have been updated for the new preprocessing flow. All time series tests pass locally.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ngupta23** [comment]
@Yard1 @tvdboom ,
 I am getting this kind of error for scipy, NumPy, and scikit-learn. I have reverted scipy and numpy to lower versions, but not sure if doing the same for scikit is what we want. I will try anyway, but if you have any other suggestions to fix the running of tests, do let me know. 

FYI.. All time series tests pass locally for me now.


```
ERROR: Could not find a version that satisfies the requirement scikit-learn>=1.0 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2, 0.22.2.post1, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.dev0, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
ERROR: No matching distribution found for scikit-learn>=1.0
Error: Process completed with exit code 1.
```

**Comment by ngupta23** [comment]
@Yard1 @tvdboom : I had to add back the silent argument in the classification/regression class `setup`. This was needed for the unit tests otherwise it complains of the wrong argument. It is not really doing anything right now (just added it so the call to `setup` does not fail). You may want to add the functionality corresponding to this argument to the code.

**Comment by tvdboom** [comment]
> @Yard1 @tvdboom , I am getting this kind of error for `scipy`, `numpy`, and `scikit-learn`. I have reverted scipy and numpy to lower versions, but not sure if doing the same for scikit is what we want. I will try anyway, but if you have any other suggestions to fix the running of tests, do let me know.
> 
> FYI.. All time series tests pass locally for me now.
> 
> ```
> ERROR: Could not find a version that satisfies the requirement scikit-learn>=1.0 (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2, 0.22.2.post1, 0.23.0rc1, 0.23.0, 0.23.1, 0.23.2, 0.24.dev0, 0.24.0rc1, 0.24.0, 0.24.1, 0.24.2)
> ERROR: No matching distribution found for scikit-learn>=1.0
> Error: Process completed with exit code 1.0
> ```

@ngupta23 When I use the latest versions of all packages (numpy, scipy, sklearn) it works just fine. Did you update pip?

**Comment by ngupta23** [comment]
> @ngupta23 When I use the latest versions of all packages (numpy, scipy, sklearn) it works just fine. Did you update pip?

@tvdboom This was on GitHub CI checks. I did not do anything specific to upgrade pip.

@Yard1 Anything we can do to update pip before running the tests on GitHub? Thanks!

**Review by tvdboom — APPROVED** [review]

**Pull request merged**
