### PR TITLE
Added python version 3.10

### LINKED ISSUE #2805: [ENH]: Add support for python 3.10
### Describe the feature you want to add to this project

Add support for python 3.10

### Describe your proposed solution

Add support for python 3.10 now that sktime supports this version of python,

### Describe alternatives you've considered, if relevant

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ngupta23**
## Related Issue or bug

Closes #2805 

#### Describe the changes you've made

- Updated tests to run using python 3.10
- Relaxed numpy settings to match sktime
- Added extras "test" to allow installation as per [developer setup]( https://github.com/pycaret/pycaret/blob/3.0.0.rc3/CONTRIBUTING.md#development-setup).

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Existing tests should pass on GitHub

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Yard1** [comment]
Spacy on windows is not working.  A quick fix would be to remove NLP tests and spacy installation from windows workflows.

**Comment by tvdboom** [comment]
Actually. The problem isn't `spacy` but `ray[tune]`.

Running `pip install -e ".[full, nlp]"` fails with `ERROR: Could not find a version that satisfies the requirement ray[tune]>=1.0.0 (from pycaret[full,nlp]) (from versions: none)`, therefore spacy is never installed. It seems ray doesn't support 3.10

**Comment by ngupta23** [comment]
> Actually. The problem isn't `spacy` but `ray[tune]`.

Related to https://github.com/ray-project/ray/issues/19116?

**Comment by ngupta23** [comment]
Per meeting on August 15th, @Yard1 mentioned that there will be a ray release next week that will support python 3.10. We will wait till then to rerun the tests.

**Comment by ngupta23** [comment]
> Per meeting on August 15th, @Yard1 mentioned that there will be a ray release soon that will support python 3.10. We will wait till then to rerun the tests.

@Yard1 It looks like this is still not released. I reran the tests and it still fails on Ray install when using python 3.10. Do you know when the official release will happen?

**Comment by ngupta23** [comment]
Per August 29th meeting, @Yard1 will look into it.

**Review by tvdboom — APPROVED** [review]

**Pull request merged**
