### PR TITLE
Implemented interactive residual plots

### PR DESCRIPTION
**Pull request by andrinbuerli**
Hello there

My name is Andrin Bürli and I am working for the ABIZ team of the Lucerne University of Applied Sciences and Arts (https://hslu.ch/abiz).
In the context of an industry project, we included some custom plots into your library.
To be exact we implemented 4 interactive residuals plots:
 - Tunkey-Anscombe
 - Scale-Location
 - Normal QQ
 - Residuals vs Leverage
 
Those plots enable us to analyse if a regression model fulfills some specific model assumtions.
Therefore they enable the user to make a plausibility check of the model for the given data.
As we are thinking that those plots are of general use we would like to propose to merge them back into your library.
Further on could those plots replace the current "Residuals" plot.

Thank you for your collaboration.

Sincerely
Andrin

### CODE REVIEW

**Comment by Yard1** [comment]
Hello Andrin,

Thank you for your contribution! Those additions look quite exciting. I'll try to review them ASAP, but I will need some time due to the amount of new code.

**Comment by Yard1** [comment]
CC @pycaret

**Comment by pycaret** [comment]
@andrinbuerli This is awesome. Thanks for your contribution. Much appreciated. Are you on our slack channel?

**Comment by pycaret** [comment]
@andrinbuerli Do you have a Notebook where can I see all the graphs that you added. Even just images would be fine if it's quick to paste here.

Thanks

**Comment by andrinbuerli** [comment]
Thanks for your feedback. No I am not yet on your slack channel. Where can I join it?
Here is a screenshot of the added plots
image
The plots are all interactive as they are implemented with plotly. If it is required, I could also create some demo notebook.

**Comment by Yard1** [comment]
@andrinbuerli Would it be possible for you to also move `internal/plotting.py` to the new plotting subpackage you've made, possibly renaming the file to something more fitting and updating references? That way we'll have everything plotting-related in one place.

**Comment by andrinbuerli** [comment]
@Yard1 I moved the file `internal/plotting.py` to `internal/plots/yellowbrick.py` and refactored the `MatplotlibDefaultDPI` context to the `helper.py` file. I would suggest that if there will be any general methods used for plotly plots, they should be implemented in a new file `internal/plots/plotly.py`. What do you think?

**Comment by Yard1** [comment]
@andrinbuerli I was wondering whether those plots can be generated with pure matplotlib. Is that possible?

**Comment by Yard1** [comment]
I see, that's understandable. If it's OK, I'll combine this PR with one that will add support for plotly in general, and make those plots available if plotly backend is chosen.

**Comment by pycaret** [comment]
@andrinbuerli Great work, man. Here is the invite link to our Slack channel: https://join.slack.com/t/pycaret/shared_invite/zt-kdoe7hee-yvNANPHXPM9VtK7R6Npx4Q

**Pull request merged**
