### PR TITLE
Fix for sktime changes in recent versions

### PR DESCRIPTION
**Pull request by ngupta23**
# Related Issue or bug

Tests were failing on CI for time series and other modules. This PR is to fix the time series tests.

# Describe the changes you've made

- `sktime` `BoxCoxTrandformer` supports negative values in recent versions. Hence, tests have been updated appropriately
- Recent versions of sktime introduced a legacy interface argument. This needs to be incorporated in Prophet Patched class in pycaret.
- Pinned sktime upper limit for now. Once the new interface is supported (along with older interface - depending on sktime version), we can remove the limit.

# Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Failing time series unit tests have been checked locally for sktime vesions 0.19.1 and 0.21.0.

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by tvdboom — APPROVED** [review]

**Comment by tvdboom** [comment]
lgtm, given that the tests pass

**Comment by ngupta23** [comment]
> lgtm, given that the tests pass

Thanks for the review. This will only clear the time series failures. :)
Other modules will have to be fixed in a separate PR.

**Review by Yard1 — APPROVED** [review]
Thanks

**Comment by ngupta23** [comment]
@tvdboom @Yard1 

It looks like tests are failing for both time series and non time series modules in python 3.7 but passing in 3.8, 3.9 and 3.10. We need to look deeper into it and decide if we need to fix python 3.7 or drop support for it.

image

**Comment by Yard1** [comment]
I think we should drop it.

**Pull request merged**
