### PR TITLE
Return train score

### LINKED ISSUE #1909: Requesting for training scores along with test scores after training models, tuning models or comparing models etc
1. Currently, after running the functions create_model, compare_model function, etc., do not return train scores, only test scores across the splits or the mean of the test scores are displayed. 
2. What if someone wants to validate the scores coming in the training sets, or how the scores are varying across the training sets? The comparison between training scores and testing scores helps us understand how the model is performing in terms of fitting, for example, overfitting, underfitting, or covariate shift. This is very crucial in the case of Time aware cross-validation.  
3. I have introduced a parameter namely return_train_score, which is a boolean variable and helps the user to specify if they want the training score to return or not. So, the choice is optional and the training score is merged with the test data frame if the parameter is set as true. I have also updated the display formats accordingly and the scores are shown as Train_Score, Test_Score, etc. 

image    

4. After the modification, the function has the outputs in the following manner, the number of scores can easily be reduced with Pycaret's own remove_metric function.
    
image
    
image
    
5. If you find this useful, I can dedicate my time to work on this issue and any suggestions on this issue are most welcome.

### PR DESCRIPTION
**Pull request by levelalphaone**
## Incorporating return train score in supervised learning models

Closes #1909

#### Describe the changes you've made

I have modified the existing metrics classes in regression and classification python file in pycaret->containers->metrics. Now, there is two class instead of every single class there, corresponding to Train and Test. I have also added return_train_score, a bool parameter to help return the training score for the train sample in the cross-validation 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] This change requires a documentation update

## How Has This Been Tested?

I have tested the code for two separate datasets, one from regression and another from classification. All the functions that has been changed in the pycaret-> regression.py or pycaret->classification.py has been tested using the example given there, with and without the added parameter.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 **original screenshot**  

image

<b>updated screenshot </b>

image

image

### CODE REVIEW

**Comment by pyaf** [comment]
Hi @moezali1, any update on this PR?

**Comment by moezali1** [comment]
@pyaf Sorry. will look soon. Can you check why build is failing?

**Comment by levelalphaone** [comment]
@moezali1 the check is failing due to the presence of the new columns in the dataframe that is being produced after the create_model function is called. I have created modified classes for the score functions to accumulate all the new scores for example 'Test_MCC' and 'Train_Accuracy' and when the test files are trying to optimize on old score names for example 'MCC' it is getting the error that the score is not found.
To get this issue resolved I would need to change the test files. So, I would change those files and create another pull request?

**Comment by pyaf** [comment]
@levelalphaone Tests are created/modified based on new features, so they are hand-in-hand with the new implementations. I don't think you have to create another PR, modify the tests in this same PR so that your added functionalities are thoroughly tested. Maybe @moezali1 can comment more on this.

**Comment by levelalphaone** [comment]
@moezali1 can you please approve the workflow, so that the test can run? I have modified the test codes as well as some other bug fixes.

**Comment by ngupta23** [comment]
@levelalphaone Lets formalize the format before we merge this in. I left some comments in #1909

**Comment by moezali1** [comment]
@ngupta23 Are we making updates on this as per our discussion the other day?

**Comment by ngupta23** [comment]
Yes @levelalphaone is making these changes. The details are in the issue linked to this PR.

**Comment by moezali1** [comment]
@levelalphaone Thanks for working on this. I am wondering if any progress has been made. It will be really nice to include this functionality in the next release (asap). After that, we will freeze the code for the 3.0 release, and may take several weeks if not months.

**Comment by levelalphaone** [comment]
@moezali1 I am really sorry for replying this late, I will be working on this and get this resolved, as soon as possible.

**Pull request closed without merging**
