### PR TITLE
Time Series - Upper and Lower Clamp

### LINKED ISSUE #1766: Add lower limit and upper limit for time series forecasting
Time series data can be naturally clamped at a limit - could be lower limit or upper limit. 
Provide an option to the user to set this limit such that the predictions and intervals do not cross it.

Reference [Link](https://www.linkedin.com/feed/update/urn:li:activity:6858135434724159488?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6858135434724159488%2C6858178529432100864%29&replyUrn=urn%3Ali%3Acomment%3A%28activity%3A6858135434724159488%2C6858189510220541952%29)

### PR DESCRIPTION
**Pull request by AJarman**
## Related Issue or bug

Info about Issue or bug

Closes #1766

#### Describe the changes you've made

Implemented upper and lower clamp(s) to predictions made in the time series models. This also applies to the prediction `y_pred` and the prediction intervals (`upper` `lower`). These are set to default `None` in `setup()` in the functional api as well as the OOP api.
If invalid values are passed, the `TypeError` is caught, warning is logged and these values are ignored in `TimeSeriesExperiment.predict()`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- I have written two tests:
    -  `test_setup_upper_and_lower_clamps_is_non_breaking()` to confirm that this is a non-breaking change to setup.py and that the TimeSeriesExperiment class instances are set as expected.
    - `test_clamp_is_enforced_on_predictions()`Confirms that the clamps are enforced and that errors are not raised when passing in non-numeric values. This also ignores np.nan values where prediction intervals are not supported by models.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
|<b>original screenshot </b> (no clamp)original| <b>updated screenshot </b> <br>(lower clamp at 400 and upper clamp at 500) clamped |

### CODE REVIEW

**Comment by AJarman** [comment]
I have found the source of the failing tests -  this occurs is when a model is saved, then loaded after being saved, but loaded into into a fresh `TimeSeriesExperiment` Object which has not had `setup` called, therefore upper_clamp and lower_clamp values are never initialised (as they are only ever set or referenced outside the constructor).

I have a few potential solutions:

- It might be a more straightforward implementation to add these (optional) parameters to `TimeSeriesExperiment.predict_model()` and the functional API function.
    - Additionally this would mean that the Experiment attributed can be overridden/ignored if no longer relevant/correct without re-doing setup and any model training. 
    - We could then remove this from `setup()` altogether if desired.
-  We could set both upper and lower clamp values to `None` in the `TimeSeriesExperiment` constructor, this would then remove the `AttributeError` when calling the API.

**Comment by AJarman** [comment]
Note that at the moment the tests are passing, however the implementation is checking is setup() has been called on the current experiment before applying the clamps.

Happy to change/enhance the implementations to those suggested above.

**Comment by Yard1** [comment]
@AJarman Could we have the clamps be applied through a sktime wrapper/meta estimator, similarly to what was done for classification probability threshold? https://github.com/pycaret/pycaret/pull/1858

**Comment by AJarman** [comment]
> @AJarman Could we have the clamps be applied through a sktime wrapper/meta estimator, similarly to what was done for classification probability threshold? That way the information about clamps would both be persisted with the model and also applied outside of pycaret, if needed. see #1858

I understand the need to be persisted across experiments/models, worth discussing

is there a time series equivalent to the superclasses defined here?:
`class CustomProbabilityThresholdClassifier(ClassifierMixin, BaseEstimator):`

**Comment by Yard1** [comment]
@ngupta23 Any idea?

**Comment by ngupta23** [comment]
Hi All, Sorry, I did not think about the persistence aspect. Not sure if this is avaiable in `sktime`. @ltsaprounis Do you have any idea if this could be implemented? Thanks!

**Comment by AJarman** [comment]
@ngupta23 
I'm quite happy to refactor this to only use the clamp kwargs in the .predict() method and remove from setup(). 

This seems like the easiest first iteration to deliver the functionality/value without the persistence as I'm not sure why someone would do that. 

We can keep the issue/open a related issue for someone to implement the wrapper/metaEstimator?

**Comment by ngupta23** [comment]
> I'm quite happy to refactor this to only use the clamp kwargs in the .predict() method and remove from setup().

The problem is that it is not only the user that needs to control the upper and lower limit in the predict_model method, but that we use predict_model internally as well in various places. So if we are to limit this, we need to add this to the setup function itself so it can be used everywhere internally (including calculation of metrics). In addition, as @Yard1 pointed out, this needs to be persisted as well in the model. So just adding it as an argument to predict_model method would not be sufficient.

We may have to table this feature unless there is a way to add it as a `sktime` model wrapper itself.

**Comment by ngupta23** [comment]
@AJarman - I spoke to @ltsaprounis yesterday. He is going to check if the clamps can be added as `sktime` transformers (a new feature in `sktime`). We should table this development until we hear back about it.

**Comment by ngupta23** [comment]
@AJarman , could you provide me a link to your LinkedIn Account so we can discuss future development efforts? Also, if you can join the pycaret slack, it would be great to discuss and align. Thanks!

https://join.slack.com/t/pycaret/shared_invite/zt-row9phbm-BoJdEVPYnGf7_NxNBP307w

**Pull request closed without merging**
