### PR TITLE
Separate y from the preprocessing pipeline

### PR DESCRIPTION
**Pull request by wkuopt**
#### Describe the changes you've made
1. Separated y from the preprocessing pipeline in PycaretExperiment.py and tested with a target remover added in the preprocessing pipeline. 
2. Also made sure the tests related to the refactored transformers (i.e., all transformers after the target remover in the pipeline, currently only the test_pca.py) passed.

This is a draft and it hasn't dealt with the encoding of y for classification problems. The proposal for the next step is to use the TransformedTargetClassifier class to wrap classifiers. @Yard1 could you take a look and see if this approach is reasonable? Thanks!

### CODE REVIEW

**Comment by Yard1** [comment]
I think it would be simpler to separate the data into X and y before passing it to the pipeline, thus removing the need for a transformer that removes the target. What do you think?

**Comment by wkuopt** [comment]
Yes I forgot to say that the target remover will be removed once the refactoring is done. It is now there just for testing purposes. Eventually we want to pass X and y separately.

**Comment by Yard1** [comment]
This is fine, then. Let me know when I can merge it.

**Comment by ngupta23** [comment]
Hi @wkuopt , Is this still in work, or should we leave it open?

**Comment by wkuopt** [comment]
Hi @ngupta23, let me remove this PR. It was meant to demonstrate how X is separated from y. I will create another PR that passes all the tests. Thanks for checking up on this!

**Pull request closed without merging**
