### PR TITLE
Adding n_jobs = -1

### PR DESCRIPTION
**Pull request by reza1615**
Solving Bug #58. adding n_jobs

### CODE REVIEW

**Comment by pycaret** [comment]
Thank you. I will take this in changes for next release.

**Comment by pycaret** [comment]
@reza1615 

Hi. Can you please submit this PR to dev-1.0.1 branch?

Thanks.

**Comment by reza1615** [comment]
> @reza1615
> 
> Hi. Can you please submit this PR to dev-1.0.1 branch?
> 
> Thanks.

Done

**Comment by pycaret** [comment]
Added into dev-1.0.1 branch separately. PR to master branch not required.

**Comment by pycaret** [comment]
@reza1615 Could you please give me your full name and email address to be included in contributor list on website. You can send me at moez@pycaret.org

**Pull request closed without merging**
