### PR TITLE
Fix docstrings & doc generation

### PR DESCRIPTION
**Pull request by Yard1**
Fixed all docstrings, aside from those in Preprocessing, to conform to numpy standard, so that sphinx can generate docs without issues. Regenerated docs. Ready to be put on readthedocs.

In the future, all documentation **must** conform to numpy standard, that is:
https://numpydoc.readthedocs.io/en/latest/format.html
https://www.sphinx-doc.org/en/master/usage/extensions/example_numpy.html

(Mostly) Fixes https://github.com/pycaret/pycaret/issues/374

### CODE REVIEW

**Comment by pycaret** [comment]
@Yard1 Thank you so much. I am going to reply to your email soon.

**Comment by pycaret** [comment]
@Yard1 Can you check the documentation of `create_model` function in documentation in any of the module. Some formatting change is required their. Name of models should appear as list.

**Comment by Yard1** [comment]
@pycaret Yeah, sorry, I forgot to mention that those tables need to be reworked into something else - bullet point lists, probably, since we can't use a proper table there. Would that be fine?

**Comment by pycaret** [comment]
Yea. Lets change them into something some bullet list so its readable.

**Comment by Yard1** [comment]
Will do. Expect a commit very soon.

**Pull request merged**
