### PR TITLE
GPU accelerated rbfsvm, rf, gbc, xgboost

### PR DESCRIPTION
**Pull request by MattiaVerticchio**
I added `rbfsvm`, `rf`, `gbc`, `xgboost` GPU acceleration in `pycaret.classification.compare_models()` using the global `gpu_param`.

### CODE REVIEW

**Comment by pycaret** [comment]
@MattiaVerticchio Thanks for working on this. Some points to start discussion:

- For `lightgbm`, `xgboost`, `catboost` we can use the built-in GPU support in the algorithms.
- `svm` and `knn` can be imported from `cuml`. I have noticed you created placeholder for `knn`, that is super helpful, thanks for that.
- `gbc` and `rf` is imported using `h204gpu`. Is this package available on `pip` and `conda`. We are in the process of creating a conda install for pycaret. Just wanna make sure, this won't be a problem. Also in the documentation, we will have to cover that the installation for `cuml` and `h204gpu` is optional and to use `use_gpu` param in `setup`, one must install these libraries separately. The way I do it is to add them in `requirements.txt` as a commented text.
- How do you plan to handle the `gpu_param` in `create_model`, `tune_model` and `blend_models` (when all is selected).

**Comment by MattiaVerticchio** [comment]
> * For `lightgbm`, `xgboost`, `catboost` we can use the built-in GPU support in the algorithms.

Exactly. GPU support for those estimators is built-in and enabled through `device='gpu'`, `tree_method='gpu_hist'` and `task_type='GPU'` parameters. I didn’t enable those flags in `CatBoostClassifier` because there were speed issues I need to investigate, as stated [here](https://github.com/pycaret/pycaret/issues/304#issuecomment-674826497).

> * `svm` and `knn` can be imported from `cuml`. I have noticed you created placeholder for `knn`, that is super helpful, thanks for that.

I also tested SVM - Linear Kernel through `cuml.MBSGDClassifier` but I got worse training times. For the same reason as `CatBoostClassifier` I didn’t include it in the pull request. Since this implementation uses mini-batches to accelerate the algorithm, we need to properly tune the `batch_size` parameter to efficiently parallelize the workload and result in an improvement over `sklearn`.

About `knn`, there’s [a bug](https://github.com/rapidsai/cuml/issues/2491) that will be solved in cuML 0.15 release that prevents scoring on large datasets, hence I opted for a placeholder to be removed when it’ solved.

> * `gbc` and `rf` is imported using `h204gpu`. Is this package available on `pip` and `conda`. We are in the process of creating a conda install for pycaret. Just wanna make sure, this won't be a problem. Also in the documentation, we will have to cover that the installation for `cuml` and `h204gpu` is optional and to use `use_gpu` param in `setup`, one must install these libraries separately. The way I do it is to add them in `requirements.txt` as a commented text.

Yes, `h2o4gpu` is available [through Conda](https://github.com/h2oai/h2o4gpu).

H2O4GPU deals with `GradientBoostingClassifier` and `RandomForest` by redirecting object calls to a properly configured [`xgboost`](https://github.com/h2oai/h2o4gpu/blob/master/src/interface_py/h2o4gpu/solvers/xgboost.py), while cuML leverages its own [CUDA libraries](https://github.com/rapidsai/cuml/blob/9d5eabbea5ff58b3520ea351b9b65e3eaf6fc4a6/python/cuml/ensemble/randomforestclassifier.pyx). Also, cuML has its own [`RandomForestClassifier`](https://docs.rapids.ai/api/cuml/stable/api.html#random-forest) but it
> is an early release of the cuML Random Forest code. It contains a few known limitations:
>
> GPU-based inference is only supported if the model was trained with 32-bit (float32) datatypes. CPU-based inference may be used in this case as a slower fallback.
>
> Very deep / very wide models may exhaust available GPU memory. Future versions of cuML will provide an alternative algorithm to reduce memory consumption.

and I would wait until it’s stable before introducing it in place of H2O4GPU’s one. I prefer cuML implementation over H2O4GPU since the first one is actively developed by Nvidia with low level CUDA kernels. Unfortunately, there is no `cuml.ensemble.GradientBoostingClassifier` implementation yet, the H2O4GPU is the only available.

> * How do you plan to handle the `gpu_param` in `create_model`, `tune_model` and `blend_models` (when all is selected).

There could be conditional imports and object creation, but it’s not very elegant and maintainable to have a lot of `if/else` statements. I like [this idea](https://github.com/pycaret/pycaret/issues/304#issuecomment-674829042) for centralizing the choice of the models.

**Comment by clgarciga** [comment]
@MattiaVerticchio Quick question on this: my understanding about RAPIDS packages is that only Linux is supported. Will this cause an error if someone is trying to use this on their Windows machine? And if so, is there a way to handle that exception so that it defaults to using sklearn?

**Comment by pycaret** [comment]
@clgarciga This is a great question. @MattiaVerticchio Same question. Would it work on windows?

**Comment by MattiaVerticchio** [comment]
RAPIDS isn’t available on Windows, a fallback to `sklearn` can be easily implemented like this:
```python
try:
    import cuml
except ImportError:
    import sklearn
```

**Comment by clgarciga** [comment]
@MattiaVerticchio Could you incorporate that try-except block in your PR?

**Comment by Yard1** [comment]
@MattiaVerticchio Are there any other models we could add from cuML?

**Comment by MattiaVerticchio** [comment]
> @MattiaVerticchio Are there any other models we could add from cuML?

There are a few models already used in PyCaret that could be added:
- `cuml.LinearRegression`
- `cuml.LogisticRegression`
- `cuml.Ridge`
- `cuml.Lasso`
- `cuml.ElasticNet`
- `cuml.ensemble.RandomForestClassifier`
- `cuml.svm.SVC`
- `cuml.svm.SVR`
- `cuml.neighbors.KNeighborsClassifier`
- `cuml.neighbors.KNeighborsRegressor`

Also, there are:
- `cuml.MBSGDClassifier`
- `cuml.MBSGDRegressor`

which are slightly different implementations of `SGDClassifier` and `SGDRegressor`.

Besides, there are a lot of routines that could accelerate preprocessing, metrics, and utilities.
Are you working on the centralized model repository?

**Comment by Yard1** [comment]
Indeed. I will contact you shortly.

**Comment by Yard1** [comment]
@MattiaVerticchio I am having issues with using RandomizedSearchCV on GPU-enabled xgboost. Could you try it yourself? Pass an XGBClassifier to tune_models. It takes an extremely long time and often crashes.

**Comment by MattiaVerticchio** [comment]
> Could you try it yourself?

I just tried, [here’s the notebook](https://colab.research.google.com/drive/1s98XWZNWkvaDEBPl0HWNE-rPZpzjFLt7?usp=sharing).
It seems that `tune_model` doesn’t get `tree_method = gpu_hist` from `**kwargs`.

**Comment by Yard1** [comment]
@MattiaVerticchio could you do `pip install git+https://github.com/Yard1/pycaret.git@refactor` instead? That way you will get the dev version.

**Comment by MattiaVerticchio** [comment]
I think the issue here is that we’re passing a cloned estimator trained with `tree_method = gpu_hist`,  to `tune_model`, which trains the model without the `gpu_hist` parameter and runs on CPU.

In the `refactor` branch we can call `tune_model(xgboost, **kwargs)`, however, by doing this I get an error from passing the `kwargs` to `RandomizedSearchCV` (that doesn’t have a `kwargs` parameter) instead of passing the parameter dictionary to the estimator.

**Comment by Yard1** [comment]
Shouldn't the parameter stay the same after cloning?

**Comment by Yard1** [comment]
Ok, resolved the issue. The `max_depth` parameter was set way too high, causing memory crashes.

**Comment by MattiaVerticchio** [comment]
> Shouldn't the parameter stay the same after cloning?

Oh yes, you’re right, now it works. 👍 



> Ok, resolved the issue. The `max_depth` parameter was set way too high, causing memory crashes.

Nice. Also, I saw `n_estimators` explicitly set up as parameter for grid search.
I usually set it really high (E.G. `9999999`) and use early stopping on cross-validation data to find the optimal number of trees without overfitting on the training set.

**Comment by Yard1** [comment]
Sadly, not every algorithm we have supports early stopping. Still, people can pass their own grids, so I don't think it will be an issue.

**Pull request closed without merging**
