### PR TITLE
Corrected RMSE container

### PR DESCRIPTION
**Pull request by tezansahu**
Initially, using `pycaret.utils.check_metric()` with RMSE gave same result as using it with MSE. Updated the RMSE container to now calculate the square root of MSE & return as the RMSE.

## Related Issuse or bug
  - Using the `check_metric()` function with `'RMSE'` yielded same result as that with `'MSE`'. In the `pycaret/containers/metrics/regression.py` file, the `score_func` for RMSE Container was incorrect (square root wasn't applied). 

Fixes: #953

#### Describe the changes you've made
Created a function `root_mean_squared_error()` in the RMSE Container class, which calculated the RMSE value. Set this function as the `score_func` for the container.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 <a href="https://imgbb.com/">Screenshot-2021-07-08-155548</a>| <a href="https://ibb.co/2nFmh1x">image</a> |

### CODE REVIEW

**Comment by Yard1** [comment]
Thanks for catching this. Looking at sklearn docs, `metrics.mean_squared_error` can return RMSE if `squared` is set to False. Can we do that instead?

**Comment by tezansahu** [comment]
Currently, the `arg` shown in the Original Screenshot tell me that `squared` is set to False, yet it is not giving me the RMSE value. Hence, I thought it would we better to create teh separate function, similar to the case of the `RMSLEMetricContainer`

**Comment by Yard1** [comment]
>>> Currently, the args shown in the Original Screenshot tell me that squared is set to False, yet it is not giving me the RMSE value. Hence, I thought it would we better to create the separate function, similar to the case of the RMSLEMetricContainer

Oh, my mistake. I didn't notice it being there. Are you sure it's not working correctly? If so, that seems to be an issue with how we apply arguments. I will take a look at it. Can you try using sklearn's `metrics.mean_squared_error` directly on some dataset with and without `squared=False`?

**Comment by Yard1** [comment]
Right, I believe I found the issue. We are ignoring the arguments when calling the function directly. Thank you for taking the time to make this PR but this should be fixed in general. I'll close it and push a fix to the underlying issue.

**Comment by tezansahu** [comment]
Ok. Thank you.

**Pull request closed without merging**
