### PR TITLE
fix for failing time series tests due to pmdarima 2.0.0

### PR DESCRIPTION
**Pull request by ngupta23**
## Related Issue or bug

Tests are failing due to the new release for pmdarima 2.0.0.

Related:  
- https://github.com/alan-turing-institute/sktime/issues/3300
- https://github.com/alan-turing-institute/sktime/pull/3301
- https://github.com/alan-turing-institute/sktime/pull/3302

#### Describe the changes you've made

Pinned pmdarima temporarily to not use 2.0.0. Will need to remove this once fixed in sktime.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Existing unit tests should pass on GitHub

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by tvdboom — APPROVED** [review]

**Review by Yard1 — APPROVED** [review]

**Comment by tvdboom** [comment]
@ngupta23 @Yard1 Any idea why windows 3.8 and 3.9 keep getting stuck during testing?

**Comment by ngupta23** [comment]
Even 3.7 was getting stuck. I reran the tests, then 3.7 passed, but 3.8 and 3.9 still timeout. I will try to rerun again.

**Comment by tvdboom** [comment]
I already reran this morning. Doesn't seem to work

**Comment by ngupta23** [comment]
> I already reran this morning. Doesn't seem to work

It seems to be getting stuck at the Fugue tests in both cases. I will disable it and check a little later.

image

**Comment by tvdboom** [comment]
What's the status of this pr @ngupta23? This issue is blocking all other prs.

**Comment by ngupta23** [comment]
> What's the status of this pr @ngupta23? This issue is blocking all other prs.

The failure is not coming from the time series part now. It is something else. I will need to see what it is.

**Comment by ngupta23** [comment]
@tvdboom @Yard1 The tests are passing when I remove the clustering tests. Can one of you look at the issue with the clustering tests?  In python 3.7, 3.8, 3.9 on Windows, this test is getting stuck (although it works in linux).

**Comment by tvdboom** [comment]
@ngupta23 I can't reproduce the error on my windows machine. The tests pass just fine

**Comment by ngupta23** [comment]
> @ngupta23 I can't reproduce the error on my windows machine. The tests pass just fine

But it fails on GitHub (stuck). So what is the next step here? Should we disable this test and continue with merge or try to figure out why it is getting stuck in GitHub?

**Comment by ngupta23** [comment]
@tvdboom  @Yard1   Let me merge for now since this is holding up other PR's but we need to eventually enable this clustering test

**Pull request merged**
