### PR TITLE
enhancement for classification models per issues/90

### PR DESCRIPTION
**Pull request by ngupta23**
Changes have only been made to the classification module. If these look acceptable, I can make them to the regression module as well.

https://github.com/pycaret/issues/90

### CODE REVIEW

**Comment by ngupta23** [comment]
I have made the changes to the classification module and submitted a pull request. If these look acceptable, I can make the same changes to the regression and clustering module as well. Thanks!

Here are examples to try out this new functionality

# Load Data and Environment
```python
from pycaret.datasets import get_data
diabetes = get_data('diabetes')

from pycaret.classification import *
exp1 = setup(diabetes, target = 'Class variable', session_id=42)
```

# Create Models

## Extra Trees Example

```python
# Existing
model = create_model('et')  
model

# with customized parameters
model = create_model('et', n_estimators=50, max_leaf_nodes=2)  
model
```

## Neural Network Example
```python
# Existing
model = create_model('mlp')
model

# with customized parameters
model = create_model('mlp', hidden_layer_sizes=(50,20,10))
model
```

## XGBoost
```python
# Existing
model = create_model('xgboost')  
model

# with customized parameters
model = create_model('xgboost', learning_rate=0.033)
model
```

# Tune Models

## Extra Trees Example

```python
# Existing
tuned_model = tune_model('et')
tuned_model

# with customized parameters
tuned_model = tune_model('et', max_leaf_nodes=400, class_weight="balanced_subsample")
tuned_model
```

## XGBoost Example
```python
# Existing
tuned_model = tune_model('xgboost')
tuned_model

# with customized parameters
tuned_model = tune_model('xgboost', reg_lambda=0.9)  
tuned_model
```

**Comment by ngupta23** [comment]
I went ahead and made the changes to all 3 modules (classification, regression and clustering). 

I guess one thing to consider is whether you would want to pass separate keyword arguments to the base estimator and to the ensemble estimator. In that case, having a names argument which takes a dictionary would be better.  An analogous example would be the `metric_params` argument as shown [here](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html).

**Comment by ngupta23** [comment]
# Clustering Examples

```python
from pycaret.clustering import *
from pycaret.datasets import get_data
data = get_data('diamond')
s = setup(data, normalize=True, session_id=42)
```

## Create Model

```python
# Existing
model = create_model('kmeans')
model
```

```python
# Custom Parameters
model = create_model('kmeans', n_init=5)
model
```

# Regression Examples

```python
from pycaret.regression import *
from pycaret.datasets import get_data
data = get_data('gold')
s = setup(data, target='Gold_T+22', session_id=42)
```
## Create Model

### Linear Regression

```python
# Existing
model = create_model('lr')
model
```

```python
# Custom Parameters
model = create_model('lr', normalize=True, fit_intercept=False)
model
```

### KNN

```python
# Existing
model = create_model('knn')
model
```

```python
# Custom Parameters
model = create_model('knn', n_neighbors = 3)
model
```
## Tune Model

```python
# Existing
model = tune_model('knn')
model
```

```python
# Custom Parameters
model = tune_model('knn', p=1)
model
```

**Comment by pycaret** [comment]
@ngupta23 

Thanks. I will merge this for now. on your keyword arguments, let me think and get back. I like the idea.

**Comment by ngupta23** [comment]
Hi, I see that this change was merged into dev and has not been taken out in the latest version of the dev branch. Any reason for this or was this an oversight?

**Pull request merged**
