### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by tvdboom**
#### Describe the changes you've made

Partially addresses #2288 

Apply black and isort (according to black profile, see [here](https://pycqa.github.io/isort/docs/configuration/black_compatibility.html)) to the whole code base 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Yard1** [comment]
@tvdboom needs update due to conflicts. Thanks for doing this!

**Comment by tvdboom** [comment]
@Yard1 I think the conflicts are due to #2530. Could you have a look at that one? thx

**Comment by tvdboom** [comment]
@ngupta23 Yes, I can do automatize it all. At least for black and isort. Ideally we would do flake8 as well but I checked and there are so many warnings that it would take me too much time and effort right now to fix those

**Comment by ngupta23** [comment]
> @ngupta23 Yes, I can do automatize it all. At least for black and isort. Ideally we would do flake8 as well but I checked and there are so many warnings that it would take me too much time and effort right now to fix those

@tvdboom that would be great. Let's start with those two (`black` and `isort`) for now. We can try to add flake8 as a separate PR. I believe there is already a precommit config file in the repo, but not sure how that is being used. Thanks!

**Comment by tvdboom** [comment]
@ngupta23 I am not sure if it's better to apply linting automatically (pre-commit) or force the person to apply it himself by testing for it and making it fail when the file would be formatted (as I have done now). Pre-commiting would mean adding something like this to the build file:

```
name: autoblack
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black .
          git config --global user.name 'autoblack'
          git config --global user.email 'cclauss@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format Python code with Black"
          git push
```

This is not very clean imo. Also would need secrets, etc. The other way would just require the person who makes the PR to run `isort pycaret`  and `black pycaret` before the PR. What do you think?

**Comment by Yard1** [comment]
Yeah I think we should just have a CI workflow that blocks the PR if black and isort checks fail. We can do a pre-commit hook later.

**Comment by ngupta23** [comment]
> This is not very clean imo. Also would need secrets, etc. The other way would just require the person who makes the PR to run `isort pycaret` and `black pycaret` before the PR. What do you think?

@tvdboom @Yard1 I think that is fair as long as future commits and PRs are forced to adhere to this styling. But then we should also update the contribution guidelines to spell this out explicitly. Currently, it mentions `precommit` with no mention for running black and isort manually.

https://github.com/pycaret/pycaret/blob/develop/CONTRIBUTING.md

**Comment by tvdboom** [comment]
@Yard1 Soudns good. Then this is it. Any idea why test_plots  is failing?

**Comment by Yard1** [comment]
@tvdboom `pytest command line usage error. Exit code 5. No tests were collected.`

Looking into it

**Comment by tvdboom** [comment]
@ngupta23 I updated the contributing file

**Review by Yard1 — APPROVED** [review]
Good to merge after CI passes. Thanks a lot!

**Pull request merged**
