### PR TITLE
added dummylogger

### PR DESCRIPTION
**Pull request by tvdboom**
## Related Issuse or bug
  - Enhancement: If experiment_name=None, don't create a log file.

#### Describe the changes you've made
create_logger returns a dummy logger (does nothing when __class__.info is called) if name=None. This approach leaves the rest of the code untouched.

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]

**Comment by pycaret** [comment]
Hi. Can we separate the system logging parameter from log_experimemt. Lets create a new parameter called system_log (default to True). The use-case for both these loggers are different.

**Comment by tvdboom** [comment]
I added the system_log parameter to (I think) all the setup functions and to the docstrings. Is it automatically added to the documentation as well?

**Comment by Yard1** [comment]
Yes, the docs are auto updated. Could we actually make it so that `system_log` param can take a Logger object too (will be used instead of `create_logger`)? That way all use cases will be covered.

**Review by Yard1 — APPROVED** [review]
Thanks, this is great

**Pull request merged**
