### PR TITLE
Fix unhandled exceptions and typos in `internal.persistence` module

### PR DESCRIPTION
**Pull request by KrishnanSG**
## Related Issue or bug
  - Unhandled exception in internal.persistence and typos

Fixes: #1323

#### Describe the changes you've made

* The `internal.persistence` module was checking imports for awscli. I have replaced it with boto3 which is the one we are actually supposed to check.
* Missing parameter values for authentication was not checked. I have added checks and log messages for it
* Docstring and log messages had couple of typos. I fixed those.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Code style update (formatting, local variables)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

No new functional change is made, so should be aligned with the previous test cases.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by pycaret** [comment]
@KrishnanSG Two quick comments:

- I think `awscli` is needed to configure the was credentials through the command line. I would assume when `awscli` is installed boto3 is also installed/upgraded automatically. Is that not correct? Can I configure as credentials without awscli? Probably not.
-  All the docstring changes made in persistence.py will have to replicated in classification.py / regression.py / clustering.py / anomaly.py as those are the docstrings users see. (In future to avoid confusion, we can just remove the docstrings from all the internal files).
- @Yard1 can comment on the technical details of PR.

**Comment by KrishnanSG** [comment]
@pycaret 

Regarding the first point, I tested that out, on installing **awscli**, boto3 isn't installed. 

These are 2 different libraries which are independent of each other.

> Q: Can I configure AWS credentials without awscli? If yes, should also be removing awscli from requirements-optional.txt?

Yes you can configure the aws credentials without the aws cli. The way to do that would be using the environment variables or shared file (~/.aws/credentials).

A more convenient way for notebook users is to pass them as env variables.

```python
import os
os.environ["AWS_ACCESS_KEY_ID "] = str("...")
os.environ["AWS_SECRET_ACCESS_KEY "] = str("...")
``` 

Here is the [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#environment-variables) for the same.

**Comment by Yard1** [comment]
Thanks, great work. Have the docs needed any changes in the public API modules? @KrishnanSG

**Review by Yard1 — APPROVED** [review]

**Comment by KrishnanSG** [comment]
@Yard1 

> Thanks, great work. Have the docs needed any changes in the public API modules? @KrishnanSG

No, only docstring for `internal.persistence.py deploy_model()` docstring was corrected

**Comment by KrishnanSG** [comment]
@Yard1 have made few changes to public docstrings. The docs would have to be refreshed.

**Review by Yard1 — APPROVED** [review]

**Comment by pycaret** [comment]
@KrishnanSG Build is failing. Can you check?

**Comment by pycaret** [comment]
@KrishnanSG I noticed classification.py has many changes. It seems like style changes. Can you confirm why that was done?

**Comment by Yard1** [comment]
@pycaret it looks to be a spacy issue (again)

**Comment by KrishnanSG** [comment]
> @KrishnanSG Build is failing. Can you check?
> 
> I also noticed `classification.py` has many changes. It seems like style changes. Can you confirm why that was done?

@pycaret
As per PEP8 standards it's advisable to use 4 spaces rather than 2 spaces which was used before.

I have auto PEP8 validator, that's the reason it has occurred.

Link to PEP8 standards: https://www.python.org/dev/peps/pep-0008/#indentation

**Comment by KrishnanSG** [comment]
@pycaret @Yard1 

Spacy has introduced a breaking change and that's the the reason why build is failing

Ref: https://spacy.io/usage/v3#migrating

**Comment by pycaret** [comment]
@KrishnanSG I have talked to @Yard1 and we suggest reverting the style changes caused by PEP8 guidelines in `classification.py` from this PR. The right way to do that would be to create a separate PR on the `time_series` branch and apply the same styling on the entire code base instead of just `classification.py`. Let's keep this PR specific to the `deploy_fix` fix and docstring updates.

**Comment by KrishnanSG** [comment]
@pycaret 
Agreed, will revert that changes and push it.

**Review by Yard1 — APPROVED** [review]

**Comment by ngupta23** [comment]
> 
> 
> > @KrishnanSG Build is failing. Can you check?
> > I also noticed `classification.py` has many changes. It seems like style changes. Can you confirm why that was done?
> 
> @pycaret
> As per PEP8 standards it's advisable to use 4 spaces rather than 2 spaces which was used before.
> 
> I have auto PEP8 validator, that's the reason it has occurred.
> 
> Link to PEP8 standards: https://www.python.org/dev/peps/pep-0008/#indentation

Plus we are using black to auto format any new code. So should probably maintain consistency there. Maybe this needs to be documented somewhere in the developers guide.

**Pull request merged**
