### PR TITLE
Create test_datasets.py

### PR DESCRIPTION
**Pull request by daikikatsuragawa**
#337

### CODE REVIEW

**Comment by pycaret** [comment]
@daikikatsuragawa Thanks. When you get a chance can you have a look at test case for nlp.py. The problem there is that build fails on travis because spacy english model must downloaded using command line for test to run. I don't know how to do that on runtime in travis.

Anyways, apart from nlp.py you can also build test cases for preprocess.py. It would be very extensive though as we might have to create multiple tests as there are many functionalities for preprocessing pipeline. So coverage will be important.  

Another easy one would be test case for **arules.py**

**Comment by daikikatsuragawa** [comment]
@pycaret  Thanks for the merge! I have seen similar issues with `nlp.py`.
Is adding `python3 -m spacy download en` to `.travis.yml` a solution to this problem?

**Comment by daikikatsuragawa** [comment]
If there is no problem, add the following code and edit `.travis.yml`.

```py
import os, sys
sys.path.insert(0, os.path.abspath(".."))

import pytest
import pycaret.nlp
import pycaret.datasets

def test():
    # loading dataset
    data = pycaret.datasets.get_data('kiva')

    # init setup
    exp_nlp101 = pycaret.nlp.setup(data = data, target = 'en', session_id = 123)
    
    # create model
    lda = pycaret.nlp.create_model('lda')

    # assign model
    lda_results = pycaret.nlp.assign_model(lda)

    # evaluate model
    pycaret.nlp.evaluate_model(lda)

    assert 1 == 1
    
if __name__ == "__main__":
    test()
```

**Comment by daikikatsuragawa** [comment]
@pycaret 
I verified. This way you will succeed!

**Comment by pycaret** [comment]
@daikikatsuragawa I am trying now. Will add `test_nlp.py` shortly.

**Pull request merged**
