### PR TITLE
Add mlflow EDA logging in setup

### LINKED ISSUE #1790: Time Series MLFlow logging during `setup`
> Additionally, all the plots that doesn't require estimator can also be lagged at a setup stage such as ACF, PACF, ts, etc.

This is a good feature to have. We will take this up later (after model MLFlow logging is implemented).

_Originally posted by @ngupta23 in https://github.com/pycaret/pycaret/issues/1782#issuecomment-955689962_

### PR DESCRIPTION
**Pull request by ryankarlos**
# Related Issue or bug

Info about Issue or bug

Closes #1790

# Describe the changes you've made

Added mlflow logging for EDA plots in setup

# Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ngupta23** [comment]
@ryankarlos Can you check why the tests are failing? Thanks!

**Comment by ryankarlos** [comment]
@ngupta23  are you able to approve the workflow again  to run ci checks - i think i was seeing similar issue on master yesterday and other independent PRs throwing same errors.

**Comment by ryankarlos** [comment]
@ngupta23  so ive switched to master and just run one of the tests that failed locally and also get errors .
Ive synced with latest master. 

Screenshot 2022-10-03 at 17 48 22

I can see this latest workflow scheduled failed on master as well, so don''t think its directly related to my additions https://github.com/pycaret/pycaret/actions/runs/3171818652/workflow

**Comment by ngupta23** [comment]
> I can see this latest workflow scheduled for master failed for the same tests, so don't think its directly related to my additions in this PR

Yes, it seems so. @Yard1 also pointed the same to me. I will need to look into it and get back to you (most likely not before the weekend though). Thanks for your patience while we work through this.

**Comment by ryankarlos** [comment]
> > I can see this latest workflow scheduled for master failed for the same tests, so don't think its directly related to my additions in this PR
> 
> Yes, it seems so. @Yard1 also pointed the same to me. I will need to look into it and get back to you (most likely not before the weekend though). Thanks for your patience while we work through this.

@ngupta23  no problem. Also, if you have any comments on my changes in this PR then let me know.

**Comment by ryankarlos** [comment]
@ngupta23 Just checking if you have had a chance to look at changes and have any comments ?

**Review by ngupta23 — APPROVED** [review]
Thanks for the PR. Approving it now.

**Pull request merged**
