### PR TITLE
Updated the License to MIT in README.md

### PR DESCRIPTION
**Pull request by Shubham2443**
## Related Issuse or bug
  - Info about Issue or bug

Fixes: #[issue number that will be closed through this PR]

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

As the LICENCE was updated to MIT and in the README.md file it was "Copyright 2021-2022 Moez Ali moez.ali@queensu.ca", It may create confussion.

## Type of change

Please delete options that are not relevant.

- [x ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [

x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **Screenshot from 2021-05-21 13-15-09**  | <b>Screenshot from 2021-05-21 13-15-42</b> |

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]

**Comment by ngupta23** [comment]
Just a suggestion. Since we already have a LICENSE file, should we just remove the licensing section from the README. It is more work to maintain it in the long run (and seems unnecessary).

**Comment by pycaret** [comment]
I agree. We should remove license details from README.md

**Comment by ngupta23** [comment]
@Shubham2443 Could you resubmit after removing the license information from the README? Thanks!

**Comment by Shubham2443** [comment]
I also agree to the above discussion.
I'll surely remove the License section from the README.md

Thanks and Regards
Shubham Kr Shaw

**Review by ngupta23 — APPROVED** [review]

**Comment by Shubham2443** [comment]
I don't have the access to merge the pull request.
Please merge.
Once it is done, I'll close this pull request.

Regards.

**Pull request merged**
