### PR TITLE
MAPE function+ decimal format

### PR DESCRIPTION
**Pull request by reza1615**
* Rewrite calculate_mape  based on https://github.com/scikit-learn/scikit-learn/pull/15007/files/a64758ef54fa1dfd8ea741dd693f1c166078f010#diff-4873478c97f8e898b176ad552a4d96a2
It should be multiply with 100
* formating training time and MAPE

### CODE REVIEW

**Comment by pycaret** [comment]
@reza1615 I think it is implied for MAPE that it is a percentage, just like R2. At the moment 11.2% MAPE is shown as 0.112. I believe your change will make it 11.2. is that right?

**Comment by reza1615** [comment]
Yes my change shows 11.2%

**Comment by pycaret** [comment]
@reza1615 Hi. I think we don't need to show % sign. It will become inconsistent because AUC, Accuracy, Recall, Precision, R2 all these metrics are presented without % sign. Can you take back the change of format change of MAPE. I like the idea of how you have centralized calculate_mape function.

**Comment by pycaret** [comment]
@reza1615 decimal format for time is also fine.

**Comment by reza1615** [comment]
@pycaret comparing to AUC, Accuracy, Recall, Precision, R2,
MAPE is the only metric which has percentage in its name and definition

**Comment by pycaret** [comment]
@reza1615 Hey Reza, what I actually meant by removing % is to remove the multiplication to 100. The formula should be same as what it was.

**Comment by reza1615** [comment]
@pycaret done

**Comment by reza1615** [comment]
@pycaret did you check the code?

**Comment by reza1615** [comment]
@pycaret : you removed the history! https://github.com/pycaret/pycaret/graphs/contributors
I don't contribute here

**Comment by pycaret** [comment]
@reza1615 This graph is only for master branch only.

**Comment by reza1615** [comment]
@pycaret I had [this](https://github.com/pycaret/pycaret/pull/74) commit  after you reuploaded the file all history removed [here ](https://github.com/pycaret/pycaret/commits/dev-1.0.1/pycaret/classification.py)

**Pull request closed without merging**
