### PR TITLE
Continuous Documentation support

### PR DESCRIPTION
**Pull request by mgautam98**
Hi
I have added the support for documentation using sphinx. You can generate the static html files on your system after installing sphinx using 
```
cd doc
make html
```

The site looks like this:
Annotation 2020-05-12 042834
Annotation 2020-05-12 042807

If you would like to publish the docs at readthedocs then I can help. Make me a collaborator there after making your account

Thanks and hope it helps

### CODE REVIEW

**Comment by pycaret** [comment]
@mgautam98 Thank you Gautam for submitting this. This is interesting. So far I have been manually managing documentation as a wordpress site but I see a huge merit in automating documentation as it sucks a lot of my time. 

In the image you shared, the formatting of docstring is obviously not correct. Do we have ways to control that? 

Yes - I also need your help in setting this on on readthedocs. 

I have never used sphinx before so would probably need a little bit more understanding and I have some questions too. Would you be open to a skype call?

Thanks.

**Comment by pycaret** [comment]
@mgautam98 Hi Gautam,

I was able to build documentation locally. It generated successfully. The formatting is obviously not right but will have to understand more on how to document docstrings appropriately for sphinx to work.

PS - I also had to install sphinx_rtd_theme as it doesn't comes in default with sphinx anymore. 

Thanks for your help again.

**Comment by mgautam98** [comment]
> In the image you shared, the formatting of docstring is obviously not correct. Do we have ways to control that?
Yes, we can control it. I used numpy doc style for this docs we can change it. There were a lot of warnings too that I would fix in next pr.

> Yes - I also need your help in setting this on on readthedocs.
Great, after building the docs as per requirement I will setup readthedocs too

**Comment by pycaret** [comment]
@mgautam98 Thanks a lot. Will wait for your next PR fixing the formatting issue in documentation.

**Comment by pycaret** [comment]
@mgautam98 Hi. Did you get a chance to work on fix of documentation formatting?

**Pull request merged**
