### PR TITLE
Refactor dependencies

### PR DESCRIPTION
**Pull request by tvdboom**
## Related Issuse or bug

Fix dependencies.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by ngupta23 — APPROVED** [review]

**Comment by ngupta23** [comment]
The failing test is due to EDA functionality in Regression/Classification (same as https://github.com/pycaret/pycaret/pull/2328). 
This should not be gating for now.

**Review by ngupta23 — APPROVED** [review]

**Comment by ngupta23** [comment]
I testes this on Colab. The issue now is that the grid does not gets displayed. Users will be forced to install ipython since we removed it from pycaret.

image

**Comment by tvdboom** [comment]
I added ipython >=5.5.0 to the requirements. This is the version colab uses. Very old but at least it works for everyone.

temp

**Comment by ngupta23** [comment]
> I added ipython >=5.5.0 to the requirements. This is the version colab uses. Very old but at least it works for everyone.

@tvdboom Can you push the changes?

**Review by Yard1 — APPROVED** [review]

**Comment by ngupta23** [comment]
@tvdboom @Yard1 

I am still not able to see the setup results. Can you try the code below and verify?

```python
!pip install -U git+https://github.com/pycaret/pycaret.git@time_series

from pycaret.datasets import get_data
from pycaret.time_series import TSForecastingExperiment

data = get_data("airline")

exp = TSForecastingExperiment()
exp.setup(data=data, fh=12, session_id=42)
```

image

**Comment by ngupta23** [comment]
> I am still not able to see the setup results. Can you try the code below and verify?

Looks to be a TimeSeries specific problem. It works for regression. I will have a look. Thanks!

**Pull request merged**
