### PR TITLE
fix target missing for multicollinearity

### PR DESCRIPTION
**Pull request by wkuopt**
## Related Issuse or bug

Fixes: #1482, #1483, #1478

#### Describe the changes you've made
Fixed the target missing error for the multicollinearity preprocessor. Added more informative error message.

## Type of change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The bug was reproduced in test_classification.py, and fixed with the new code.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by wkuopt** [comment]
Committed with wrong account, will create the PR again

**Comment by zingochampis** [comment]
Stll not working, is it because of this commit under wrong account?

**Comment by wkuopt** [comment]
Are you using the latest code from the master branch?

**Comment by zingochampis** [comment]
@wkuopt I pip-istall pycaret[full] with --upgrade --force-reinstall. also tried same with pycare-nightly[full]. Does this get me to master branch?

**Comment by wkuopt** [comment]
@zingochampis pycaret-nightly contains the fix. Can you provide your dataset, code, and error message so that I can reproduce the error?

**Comment by zingochampis** [comment]
@wkuopt  I have messed up the installation of nightly. Reinstalling it helped.

**Pull request closed without merging**
