### PR TITLE
fix bugs in preprocessing, predict_model and create_app

### LINKED ISSUE #2757: [BUG]: create_app not removing one-hot codded columns
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When I try to run create_app() in the latest master, it doesn't remove the one-hot codded columns. So it shows the error below in the actual result section.

### Reproducible Example

```python
!pip install -U git+https://github.com/pycaret/pycaret.git@master
!pip install gradio --quiet

from pycaret.regression import *
from pycaret.datasets import get_data

boston = get_data('bank')
exp_name = setup(data = boston,  target = 'deposit')
lr = create_model('lr')
create_app(lr)
```

### Expected Behavior

Display URL of gradio

### Actual Results

```python-traceback
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-f9dc2e4d736f> in <module>()
      5 exp_name = setup(data = boston,  target = 'deposit')
      6 lr = create_model('lr')
----> 7 create_app(lr)

5 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py in _validate_read_indexer(self, key, indexer, axis)
   1375 
   1376             not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 1377             raise KeyError(f"{not_found} not in index")
   1378 
   1379 

KeyError: "['marital_single', 'marital_married', 'marital_divorced', 'education_secondary', 'education_primary', 'education_tertiary', 'education_unknown', 'contact_cellular', 'contact_unknown', 'contact_telephone', 'poutcome_success', 'poutcome_unknown', 'poutcome_failure', 'poutcome_other'] not in index"
```

### Installed Versions

<details>

System:
    python: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
executable: /usr/bin/python3
   machine: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

PyCaret required dependencies:
                 pip: 21.1.3
          setuptools: 57.4.0
             pycaret: 3.0.0.rc3
             IPython: 5.5.0
          ipywidgets: 7.7.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.3.5
              jinja2: 2.11.3
               scipy: 1.7.3
              joblib: 1.1.0
             sklearn: 1.0.2
                pyod: Installed but version unavailable
            imblearn: 0.8.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1</details>

### LINKED ISSUE #2813: [BUG]: raw_score = True removes the score column completely
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When raw_score is set to true when calling predict_model, no score is available for any label. 
Documentation says raw_score = True should return scores for each label.

### Reproducible Example

```python
from pycaret.classification import *
from pycaret.datasets import get_data

exp = ClassificationExperiment()
df = get_data('juice')
exp.setup(df)
model = exp.create_model('rf')
pred = exp.predict_model(model, raw_score = True)
pred.columns
```

### Expected Behavior

Scores for all labels should be returned.

### Actual Results

```python-traceback
The 'Score' column is removed from the predicted dataset, compared to if raw_score=False. 
No score for each label is returned.

Index(['Id', 'Purchase', 'WeekofPurchase', 'StoreID', 'PriceCH', 'PriceMM',
       'DiscCH', 'DiscMM', 'SpecialCH', 'SpecialMM', 'LoyalCH', 'SalePriceMM',
       'SalePriceCH', 'PriceDiff', 'Store7', 'PctDiscMM', 'PctDiscCH',
       'ListPriceDiff', 'STORE', 'Label'],
      dtype='object')
```

### Installed Versions

<details>
'3.0.0.rc3'
</details>

### LINKED ISSUE #2853: [BUG]: data engineering problem or bug or nothing? (give me a better title)
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I found a problem that may be rare, but it exists. Help me understand how pycaret should deal with this problem. Here goes:

In my code (football analysis) there is the following situation. A feature "posse_de_bola_casa" and "posse_de_bola_fora"  with numeric values.

so to know who has the highest value I did:
```
for index, row in dados_treino.iterrows():        
    if row['posse_de_bola_casa'] > row['posse_de_bola_fora']:
        dados_treino.loc[index, 'posse_de_bola'] = 'casa'
    elif row['posse_de_bola_casa'] < row['posse_de_bola_fora']:
        dados_treino.loc[index, 'posse_de_bola'] = 'fora'
    elif row['posse_de_bola_casa'] == row['posse_de_bola_fora']:
        dados_treino.loc[index, 'posse_de_bola'] = 'igual'
```

to understand what has happened so far: i have 2 features "posse_de_bola_casa" and "posse_de_bola_fora" with numeric values and with that i created a new feature "posse_de_bola" with possible values "casa", "fora" or "igual".

The problem is after or in setup because it create new features with suffix values. It means it will try create "posse_de_bola" into existent features, because the values can´t be a suffix.

I hope you understand that. To solve this for me is easy, i only need change features names or values.

Major question: What can pycaret do in such a situation?

Maybe detect this situation and change the feature names for example with a prefix "nf_" (from new feature) or improve the error messages, or any ideas?

### Reproducible Example

```python
.
```

### Expected Behavior

.

### Actual Results

```python-traceback
ValueError                                Traceback (most recent call last)
Input In [44], in <cell line: 2>()
      1 # golos_tr_>_0_5
----> 2 s = setup(data=dados_treino, target='vencedor_tr', numeric_imputation='knn', ignore_features=['ronda', 'tipo_de_jogo'], fix_imbalance=True, normalize=True, max_encoding_ohe=8, fold=6, use_gpu=True, session_id=1)

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\classification\functional.py:564, in setup(data, data_func, target, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    562 exp = _EXPERIMENT_CLASS()
    563 set_current_experiment(exp)
--> 564 return exp.setup(
    565     data=data,
    566     data_func=data_func,
    567     target=target,
    568     train_size=train_size,
    569     test_data=test_data,
    570     ordinal_features=ordinal_features,
    571     numeric_features=numeric_features,
    572     categorical_features=categorical_features,
    573     date_features=date_features,
    574     text_features=text_features,
    575     ignore_features=ignore_features,
    576     keep_features=keep_features,
    577     preprocess=preprocess,
    578     imputation_type=imputation_type,
    579     numeric_imputation=numeric_imputation,
    580     categorical_imputation=categorical_imputation,
    581     iterative_imputation_iters=iterative_imputation_iters,
    582     numeric_iterative_imputer=numeric_iterative_imputer,
    583     categorical_iterative_imputer=categorical_iterative_imputer,
    584     text_features_method=text_features_method,
    585     max_encoding_ohe=max_encoding_ohe,
    586     encoding_method=encoding_method,
    587     polynomial_features=polynomial_features,
    588     polynomial_degree=polynomial_degree,
    589     low_variance_threshold=low_variance_threshold,
    590     group_features=group_features,
    591     group_names=group_names,
    592     remove_multicollinearity=remove_multicollinearity,
    593     multicollinearity_threshold=multicollinearity_threshold,
    594     bin_numeric_features=bin_numeric_features,
    595     remove_outliers=remove_outliers,
    596     outliers_method=outliers_method,
    597     outliers_threshold=outliers_threshold,
    598     fix_imbalance=fix_imbalance,
    599     fix_imbalance_method=fix_imbalance_method,
    600     transformation=transformation,
    601     transformation_method=transformation_method,
    602     normalize=normalize,
    603     normalize_method=normalize_method,
    604     pca=pca,
    605     pca_method=pca_method,
    606     pca_components=pca_components,
    607     feature_selection=feature_selection,
    608     feature_selection_method=feature_selection_method,
    609     feature_selection_estimator=feature_selection_estimator,
    610     n_features_to_select=n_features_to_select,
    611     custom_pipeline=custom_pipeline,
    612     custom_pipeline_position=custom_pipeline_position,
    613     data_split_shuffle=data_split_shuffle,
    614     data_split_stratify=data_split_stratify,
    615     fold_strategy=fold_strategy,
    616     fold=fold,
    617     fold_shuffle=fold_shuffle,
    618     fold_groups=fold_groups,
    619     n_jobs=n_jobs,
    620     use_gpu=use_gpu,
    621     html=html,
    622     session_id=session_id,
    623     system_log=system_log,
    624     log_experiment=log_experiment,
    625     experiment_name=experiment_name,
    626     experiment_custom_tags=experiment_custom_tags,
    627     log_plots=log_plots,
    628     log_profile=log_profile,
    629     log_data=log_data,
    630     verbose=verbose,
    631     memory=memory,
    632     profile=profile,
    633     profile_kwargs=profile_kwargs,
    634 )

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\classification\oop.py:850, in ClassificationExperiment.setup(self, data, data_func, target, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, engines, verbose, memory, profile, profile_kwargs)
    847 if ("placeholder", None) in self.pipeline.steps and len(self.pipeline) > 1:
    848     self.pipeline.steps.remove(("placeholder", None))
--> 850 self.pipeline.fit(self.X_train, self.y_train)
    852 self.logger.info("Finished creating preprocessing pipeline.")
    853 self.logger.info(f"Pipeline: {self.pipeline}")

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\internal\pipeline.py:153, in Pipeline.fit(self, X, y, **fit_params)
    151 def fit(self, X=None, y=None, **fit_params):
    152     fit_params_steps = self._check_fit_params(**fit_params)
--> 153     X, y, _ = self._fit(X, y, **fit_params_steps)
    155     with _print_elapsed_time("Pipeline", self._log_message(len(self.steps) - 1)):
    156         if self._final_estimator != "passthrough":

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\internal\pipeline.py:134, in Pipeline._fit(self, X, y, **fit_params_steps)
    131         cloned = clone(transformer)
    133     # Fit or load the current transformer from cache
--> 134     X, y, fitted_transformer = self._memory_fit(
    135         transformer=cloned,
    136         X=X,
    137         y=y,
    138         message=self._log_message(step_idx),
    139         **fit_params_steps.get(name, {}),
    140     )
    142 # Replace the transformer of the step with the fitted
    143 # transformer (necessary when loading from the cache)
    144 self.steps[step_idx] = (name, fitted_transformer)

File ~\anaconda3\envs\teste2\lib\site-packages\joblib\memory.py:594, in MemorizedFunc.__call__(self, *args, **kwargs)
    593 def __call__(self, *args, **kwargs):
--> 594     return self._cached_call(args, kwargs)[0]

File ~\anaconda3\envs\teste2\lib\site-packages\joblib\memory.py:537, in MemorizedFunc._cached_call(self, args, kwargs, shelving)
    534         must_call = True
    536 if must_call:
--> 537     out, metadata = self.call(*args, **kwargs)
    538     if self.mmap_mode is not None:
    539         # Memmap the output at the first call to be consistent with
    540         # later calls
    541         if self._verbose:

File ~\anaconda3\envs\teste2\lib\site-packages\joblib\memory.py:779, in MemorizedFunc.call(self, *args, **kwargs)
    777 if self._verbose > 0:
    778     print(format_call(self.func, args, kwargs))
--> 779 output = self.func(*args, **kwargs)
    780 self.store_backend.dump_item(
    781     [func_id, args_id], output, verbose=self._verbose)
    783 duration = time.time() - start_time

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\internal\pipeline.py:70, in _fit_transform_one(transformer, X, y, message, **fit_params)
     68 """Fit and transform the data using one transformer."""
     69 _fit_one(transformer, X, y, message, **fit_params)
---> 70 X, y = _transform_one(transformer, X, y)
     72 return X, y, transformer

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\internal\pipeline.py:46, in _transform_one(transformer, X, y)
     44 if "y" in signature(transformer.transform).parameters:
     45     args.append(y)
---> 46 output = transformer.transform(*args)
     48 if isinstance(output, tuple):
     49     X, y = output[0], output[1]

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\internal\preprocess\transformers.py:243, in TransformerWrapper.transform(self, X, y)
    241 else:
    242     if len(output.shape) > 1:
--> 243         new_X = self._prepare_df(X, output)
    244         new_y = y if y is None else y.set_axis(new_X.index)
    245     else:

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\internal\preprocess\transformers.py:178, in TransformerWrapper._prepare_df(self, X, out)
    176 # Reorder columns if only a subset was used
    177 if len(self._include) != X.shape[1]:
--> 178     return self._reorder_cols(out, X)
    179 else:
    180     return out

File ~\anaconda3\envs\teste2\lib\site-packages\pycaret\internal\preprocess\transformers.py:118, in TransformerWrapper._reorder_cols(self, df, original_df)
    116 for col in df:
    117     if col in original_df and col not in self._include:
--> 118         raise ValueError(
    119             f"Column '{col}' returned by the transformer "
    120             "already exists in the original dataset."
    121         )
    123 # Force new indices on old dataset for merge
    124 try:

ValueError: Column 'posse_de_bola_casa' returned by the transformer already exists in the original dataset.
```

### Installed Versions

<details>
System:
    python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\username\anaconda3\envs\teste2\python.exe
   machine: Windows-10-10.0.22622-SP0

PyCaret required dependencies:
                 pip: 22.2.2
          setuptools: 60.10.0
             pycaret: 3.0.0.rc3
             IPython: 8.4.0
          ipywidgets: 7.7.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.4.3
              jinja2: 3.0.3
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.2
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2.99
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1
</details>

### LINKED ISSUE #2872: [BUG]:ValueError: 'fill_value'=constant is invalid. Expected a numerical value when imputing numerical data
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

This error is thrown in Setup when Preprocess = True and fix_imbalance_method=smote and fix_imbalance=True for classification

### Reproducible Example

```python
No `object` columns are present in the dataframe. All are int/float
```

### Expected Behavior

No Error

### Actual Results

```python-traceback
---> 79 fix_imbalance_method=smote,fix_imbalance=True)

10 frames
/usr/local/lib/python3.7/dist-packages/sklearn/impute/_base.py in fit(self, X, y)
    338                 "'fill_value'={0} is invalid. Expected a "
    339                 "numerical value when imputing numerical "
--> 340                 "data".format(fill_value)
    341             )
    342 

ValueError: 'fill_value'=constant is invalid. Expected a numerical value when imputing numerical data
```

### Installed Versions

<details>
3.0.0rc
</details>

### PR DESCRIPTION
**Pull request by tvdboom**
## Related Issue or bug

Closes #2853
Closes #2813
Closes #2757
Fixes #2872

#### Describe the changes you've made

* Fixed a bug where encoders would be added to the pipeline unnecessary
* Fixed a bug where predict_model with raw_score=True would fail
* Fixed a bug where create_app would fail when the pipelien created new columns
* Improved error message for transformers that return existing columns
* Fixed a bug where iterative imputation parameters were displayed when imputer_type=None

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by jonasvdd** [comment]
Hi, sure! this can be achieved in `plotly-resampler==0.8.1`, which will be released somewhere later this week!
Keep you posted

**Comment by jonasvdd** [comment]
Hi, the just-released `plotly-resampler==0.8.1` should fix this, additionally, the `numpy` pre-install hack for CI testing which was added in https://github.com/pycaret/pycaret/pull/2671 should not be required anymore! 🎉

**Comment by ngupta23** [comment]
Per the August 29th meeting, we decided to separate out the `deepchecks` issue since it pins `plotly` to 0.5.5 which makes the code incompatible with pycaret. Before adding deep checks, we were installing `ploty` 0.5.10 by default which works with pycaret. 

The decision was to separate out the addition of `deepchecks` from this PR and fix that issue separately (hopefully on the deepcheck side by relaxing requirements).

image

image

**Review by ngupta23 — APPROVED** [review]

**Comment by ItayGabbay** [comment]
Hey @ngupta23 
Deepchecks maintainer here. Just letting you guys know we've finally released a new version (0.9.2) that relaxes this strict requirement.

**Pull request merged**
