### PR TITLE
Update optuna to v3

### PR DESCRIPTION
**Pull request by keisuke-umezawa**
## Related Issue or bug

Related: https://github.com/optuna/optuna/issues/2941

#### Describe the changes you've made

In Optuna v3, we will introduce FloatDistribution and IntDistribution. So distributions in pycaret will have to be updated:

* UniformDistribution(low, high) => FloatDistribution(low, high)
* DiscreteUniformDistribution(low, high, q) => FloatDistribution(low, high, step)
* LogUniformDistribution(low, high) => FloatDistribution(low, high, log=True)
* IntUniformDistribution(low, high) => IntDistribution(low, high)
* IntUniformDistribution(low, high, step) => IntDistribution(low, high, step)
* IntLogUniformDistribution(low, high) => IntDistribution(low, high, log=True)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Dependent library update

## How Has This Been Tested?

By the unit test in the repository

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Yard1** [comment]
Hey @keisuke-umezawa, thanks for the PR, it's highly appreciated! Any chance we can make sure the PR is backwards compatible?

**Comment by keisuke-umezawa** [comment]
@Yard1 
Thank you for the comment.

> the PR is backwards compatible

If the meaning of the backwards compatibility here is that we can run pycaret with both Optuna v2.x and v3.x, we should not merge this PR. This code change can run with Optuna v3.x.

As Optuna will keep the backwards compatibility for a while, e.g. until v4, we do not need to merge this PR at the moment. But, in that case, one note is that someone needs to merge this PR when Optuna will totally break the backwards compatibility.

**Comment by Yard1** [comment]
Yes, we would like to be able to keep compatibility with Optuna v2. Could we perhaps have 2 cases - one for v2, and one for v3 (if eg. `FloatDistribution` cannot be imported, use the current ones).

**Comment by keisuke-umezawa** [comment]
@Yard1 
> Yes, we would like to be able to keep compatibility with Optuna v2. Could we perhaps have 2 cases - one for v2, and one for v3 (if eg. FloatDistribution cannot be imported, use the current ones).

To address your comment, I checked the version of optuna and dispatched calling of functions. The implementation seems to be redundant, but it should work.

**Review by Yard1 — APPROVED** [review]
Thanks, much appreciated! Will merge after CI passes.

**Pull request merged**
