### PR TITLE
[Bug Fix] Fixed issues caused by old deprecated `pandas-profiling` library to new updated `ydata-profiling` 

### LINKED ISSUE #3645: [BUG]: 'pandas_profiling' is now 'ydata-profiling'. ModuleNotFoundError:  'pandas_profiling' is a soft dependency and not included in the pycaret installation.
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [x] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

The latest release of pycaret (version 3.0.4) still references the old [pandas-profiling](https://pypi.org/project/pandas-profiling/) library in [source code](https://github.com/pycaret/pycaret/blob/master/pycaret/internal/pycaret_experiment/tabular_experiment.py#L208). According to the official documentation, pandas-profiling has been converted to [ydata-profiling](https://github.com/ydataai/ydata-profiling).

To ensure compatibility and utilize the updated functionality of ydata-profiling, it is necessary to update the  [source code](https://github.com/pycaret/pycaret/blob/master/pycaret/internal/pycaret_experiment/tabular_experiment.py#L208) to use ydata-profiling instead of pandas-profiling.

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.regression import setup
dataset = get_data("diamond")
dataset1 = get_data("diamond", profile=True)
```

### Expected Behavior

It should give profiling report but it doesn't. 

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-41-f9ca271b0078> in <cell line: 1>()
----> 1 dataset1 = get_data("diamond", profile=True)

1 frames
/usr/local/lib/python3.10/dist-packages/pycaret/utils/_dependencies.py in _check_soft_dependencies(package, severity, extra, install_name)
    150         if severity == "error":
    151             logger.exception(f"{msg}")
--> 152             raise ModuleNotFoundError(msg)
    153         elif severity == "warning":
    154             logger.warning(f"{msg}")

ModuleNotFoundError: 
'pandas_profiling' is a soft dependency and not included in the pycaret installation. Please run: `pip install pandas-profiling` to install.
Alternately, you can install this by running `pip install pycaret[analysis]`
```

### Installed Versions

<details>
System:
    python: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0]
executable: /usr/bin/python3
   machine: Linux-5.15.109+-x86_64-with-glibc2.31

PyCaret required dependencies:
                 pip: 23.1.2
          setuptools: 67.7.2
             pycaret: 3.0.4
             IPython: 7.34.0
          ipywidgets: 7.7.1
                tqdm: 4.65.0
               numpy: 1.22.4
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.10.1
              joblib: 1.3.1
             sklearn: 1.2.2
                pyod: 1.1.0
            imblearn: 0.10.1
   category_encoders: 2.6.1
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.27.1
          matplotlib: 3.7.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.13.1
    plotly-resampler: Not installed
             kaleido: 0.2.1
           schemdraw: 0.15
         statsmodels: 0.13.5
              sktime: 0.20.1
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.5
          markupsafe: 2.1.3
             pickle5: Not installed
         cloudpickle: 2.2.1
         deprecation: 2.1.0
              xxhash: 3.2.0
           wurlitzer: 3.0.3

PyCaret optional dependencies:
                shap: 0.42.1
           interpret: 0.4.2
                umap: 0.5.3
    pandas_profiling: Not installed
  explainerdashboard: Installed but version unavailable
             autoviz: 0.1.730
           fairlearn: 0.7.0
          deepchecks: 0.17.3
             xgboost: 1.7.6
            catboost: Not installed
              kmodes: Not installed
             mlxtend: 0.22.0
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: Not installed
            hyperopt: 0.2.7
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: 1.1.4
</details>

### PR DESCRIPTION
**Pull request by beingmechon**
# Related Issue or bug

Info about Issue or bug

Closes #3645

# Describe the changes you've made

Updated the old deprecated libraries to newly updated libraries in the source code. 

# Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested the package on my forked [repo](https://github.com/beingmechon/pycaret.git).
Test can be produced using the following set of code 

```
!pip install git+https://github.com/beingmechon/pycaret.git
!pip install ydata-profiling

from pycaret.datasets import get_data
from pycaret.regression import setup
dataset1 = get_data("diamond", profile=True)
```

# Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

`NA`

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

# Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by ngupta23** [comment]
Hi @beingmechon - Could you fix the code quality issues, please? Thanks!

**Comment by beingmechon** [comment]
> Hi @beingmechon - Could you fix the code quality issues, please? Thanks!

Hello @ngupta23 fixed the code quality issues. Thank you

**Review by ngupta23 — APPROVED** [review]

**Comment by ngupta23** [comment]
@beingmechon Thanks for your first contribution. The PR has been merged.

**Comment by beingmechon** [comment]
> @beingmechon Thanks for your first contribution. The PR has been merged.

Thank you @ngupta23

**Pull request merged**
