### PR TITLE
Adding WOE encoder (2)

### PR DESCRIPTION
**Pull request by reza1615**
Bug #65

### CODE REVIEW

**Comment by reza1615** [comment]
@pycaret would you please merge this request?

**Comment by pycaret** [comment]
@reza1615 Hi.

I am still working on this. I have never used WOE encoders before. Do you have any test case or example you have created for this?

Thanks.

**Comment by reza1615** [comment]
@pycaret WOE is very useful for financial tasks [source]( https://blogs.oracle.com/r/computing-weight-of-evidence-woe-and-information-value-iv)
Unit test
[WOE unit test.zip](https://github.com/pycaret/pycaret/files/4553429/WOE.unit.test.zip)

**Comment by reza1615** [comment]
@pycaret Did you check?

**Comment by reza1615** [comment]
@pycaret: You removed the history! https://github.com/pycaret/pycaret/graphs/contributors
I don't contribute here.

**Pull request closed without merging**
