### PR TITLE
Resolve blockers to using cuML as a computational backend

### LINKED ISSUE #2914: [BUG]: Unable to use GPU for classification
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Setup not working with GPU enabled. 

### Reproducible Example

```python
import mlflow
from pycaret.classification import *
from imblearn.over_sampling import SMOTE
import pandas as pd


data = pd.DataFrame({'V1': [-1.34419, -1.89211, 1.69421, 0.263328, 0.107918, 0.154241, 0.33468, 1.447778, -0.918269, 0.86319, -1.630049, 1.643798, 1.274341, -1.296742, -0.193585, 1.627422, -0.66805, -1.664491, -1.86911, 0.892885],
                     'V2': [0.85556, -1.70503, -0.02896, 1.746258, -0.084151, 1.673185, 1.113326, -0.23231, 1.054817, -1.407584, 0.474997, 0.150687, -0.738246, -0.045513, 1.58637, 0.984249, 0.624333, 0.298866, 0.662204, 0.967942],
                     'V3': [1.768638, -0.503169, -0.25622, -0.937752, -0.062189, -0.820652, -1.786942, -1.770495, 1.808681, -0.280286, -1.389736, 0.182212, -0.602959, -0.354683, -1.065631, 1.649264, 0.389538, -1.674815, 0.281824, -1.683662],
                     'V4': [1.512828, 1.177697, -1.156862, -1.877876, 1.526013, 1.644001, -1.282481, -0.720543, 0.323963, -1.931616, 1.632839, 1.706752, 1.895627, 1.860705, -1.559702, 1.517466, 1.254323, 1.84415, -1.175013, -1.600652],
                     'V5': [0.820483, -1.20923, -0.012221, 1.682836, 0.104248, 1.258085, 0.404062, 0.18019, 1.352545, -0.497071, 0.771277, 1.614052, -0.693854, 0.002655, 0.277743, -0.977744, -0.97259, -1.501586, -0.731194, -0.551264],
                     'V6': [1.079115, -0.734152, -1.630816, -1.877664, 1.577477, -1.902078, 1.012828, -1.107726, 1.742781, -1.338595, 1.788969, -0.851507, 1.061596, -0.635559, -1.171469, -1.001642, 1.493507, 0.732088, 1.565327, -1.845441],
                     'V7': [1.165929, 1.804607, 0.886589, -0.027458, -1.444197, -0.415643, 0.863924, -1.177661, 1.684514, 1.023797, -1.234116, -0.989024, 0.815575, -0.668453, 0.591911, -0.798925, 1.024032, -1.983963, 1.900752, 1.201001],
                     'V8': [-0.536923, 0.641581, -0.585228, 1.061145, -0.303192, -0.652068, 0.858556, 0.11012, 1.839738, -1.51798, -0.942028, -0.736386, -0.098261, 0.699127, 0.173854, -1.16775, -0.417662, 0.021639, 1.745042, -1.119667],
                     'V9': [0.643498, -1.090347, 0.120182, -0.819219, -1.296763, 0.530723, -1.367664, -0.708116, -1.304274, 1.486166, 1.656498, 1.645308, -0.257558, 0.400849, 1.356781, 1.693433, 0.42606, 0.370683, -0.239278, -0.541334],
                     'V10': ['JDckkIYygiXbraGzFone', 'xNDWMgkntdCNryqCMEYs', 'krXoQLpmApEWUiIWVbmJ', 'lXYmEHLoYnFPSHtXcEuu', 'OEhEeAHiZmhfmHDsHBgs', 'ajJnCMGurcQvUpQjYZTr', 'rZcQVNobsMFgvcxptHWo', 'vrMZETWVTYpsSGsVAGxa', 'wEZFihTPVUQxLYgDmrUs', 'jvIivwBJVFkkOzajfYWF', 'aUyTUQywDuazODSIYevH', 'vmnXmKNrCPdkQzCjrhHY', 'cRpaHTACAxzVKFaNrlxV', 'eVpGixWFesULQAusLAlX', 'wdCWfBEnwVfuKBtvGmCT', 'zaREhwuKnvFBYGtsbzuH', 'kMhPxKpcPZKWigmqhdrd', 'SyZYKzmfwGHdqpwGUgMu', 'uEMwhIsimAuiMFxkplib', 'fpoQSTBgObgfAtFoGDnG'],
                     'V11': ['xEGVWWvLSfwQuCxqutSF', 'JzPorPhjGdykesTHOMOv', 'gpgQwfJXhuYnWievuROR', 'VnWVyzcwiFDrjuBaUIrR', 'lxtRHDLNulVeSbRxbZoX', 'EfLyHSUocfMmZyNRfSeC', 'NrKUvrkVbUuanjzATNuv', 'bgrODfsyrKoliOTfqZGR', 'zKsqqcyavoHNgJCBxcNp', 'xNYdswhLjkzrPlikqowb', 'lVWRydNfhzjQDrbvHpjh', 'zgWNWUasSvjrOgTvqljR', 'wZvvIelZzLFMoIUYYtwZ', 'pTApGzbogqlDbbJuwkaC', 'YqQEiUIuTQWkKHwySzsi', 'biAKKxFxcwyozXeQCUPY', 'NezNDVIGvQQwvjLgBAwL', 'aCKbSkFtxnYxVUzaQbDF', 'sDnocrGwqzUzikLNbkCz', 'MqqoWoweqRCHzKIKcBmS'],
                     'V12': ['TWkHKaRyVrKpnbjFkTGo', 'rempSuVAtaiTBEKbupQI', 'xlCQxuxgqRPchltKkNPf', 'OXfVOPTuCVrgFIVHDCgA', 'oWZCCXyqgWkRKXyqGBkR', 'YxuwVyyvtdRFFTiwQPJU', 'QcmeBjTaAlItPpQwEkKB', 'oZwqbBSlkEqFCkePFGKu', 'aejtRakmpjtqBdMcNxwt', 'hNdJhpxtMGNlmSVZmSZb', 'OgarOKDltZCewJQnTbGl', 'NjPEwdMvPvURwTXYgRlB', 'vpBCoZQuWcxNmicUyPzv', 'FULHNkNvxDcwlLLnYAZJ', 'GyDiIfHYnPWdvGEtVhhR', 'QZaMucATTIKMaGQDWiMF', 'prOhZeiROgtCXnHaGWSI', 'DnOadsbpYbyTaeZnAuAx', 'LacKToudkichSDIhlmUv', 'pOdJWvhSHkkrrLbDSvey'],
                     'Class': [1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1]})


setup(data=data,
      target='Class',
      train_size=0.7,
      test_data=None,
      ordinal_features=None,
      numeric_features=['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9'],
      categorical_features=['V10','V11','V12'],
      text_features=None,
      ignore_features=None,
      keep_features=None,
      preprocess=True,
      imputation_type='simple',
      numeric_imputation='mean',
      categorical_imputation='constant',
      max_encoding_ohe=5,
      polynomial_features=True,
      polynomial_degree=4,
      low_variance_threshold=None,
      group_features=None,
      group_names=None,
      remove_multicollinearity=False,
      multicollinearity_threshold=0.9,
      bin_numeric_features=None,
      remove_outliers=False,
      fix_imbalance=True,
      fix_imbalance_method=SMOTE(),
      transformation=True,
      transformation_method='yeo-johnson',
      normalize=True,
      normalize_method='zscore',
      pca=False,
      feature_selection=True,
      feature_selection_method='classic', 
      feature_selection_estimator='lightgbm', 
      n_features_to_select=10,
      custom_pipeline=None,
      custom_pipeline_position=-1,
      data_split_shuffle=True,
      data_split_stratify=True,
      fold_strategy='stratifiedkfold',
      fold=10,
      fold_shuffle=False,
      fold_groups=None,
      n_jobs=-1,
      use_gpu=True,
      html=True,
      session_id=123,
      log_experiment=True,
      system_log=True,
      experiment_name='pycaret3_test',
      experiment_custom_tags=None,
      # engines=None,
      verbose=True,
      memory=True
     )
```

### Expected Behavior

Setup should complete successfully. 

### Actual Results

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [10], in <cell line: 22>()
      4 import pandas as pd
      7 data = pd.DataFrame({'V1': [-1.34419, -1.89211, 1.69421, 0.263328, 0.107918, 0.154241, 0.33468, 1.447778, -0.918269, 0.86319, -1.630049, 1.643798, 1.274341, -1.296742, -0.193585, 1.627422, -0.66805, -1.664491, -1.86911, 0.892885],
      8                      'V2': [0.85556, -1.70503, -0.02896, 1.746258, -0.084151, 1.673185, 1.113326, -0.23231, 1.054817, -1.407584, 0.474997, 0.150687, -0.738246, -0.045513, 1.58637, 0.984249, 0.624333, 0.298866, 0.662204, 0.967942],
      9                      'V3': [1.768638, -0.503169, -0.25622, -0.937752, -0.062189, -0.820652, -1.786942, -1.770495, 1.808681, -0.280286, -1.389736, 0.182212, -0.602959, -0.354683, -1.065631, 1.649264, 0.389538, -1.674815, 0.281824, -1.683662],
   (...)
     18                      'V12': ['TWkHKaRyVrKpnbjFkTGo', 'rempSuVAtaiTBEKbupQI', 'xlCQxuxgqRPchltKkNPf', 'OXfVOPTuCVrgFIVHDCgA', 'oWZCCXyqgWkRKXyqGBkR', 'YxuwVyyvtdRFFTiwQPJU', 'QcmeBjTaAlItPpQwEkKB', 'oZwqbBSlkEqFCkePFGKu', 'aejtRakmpjtqBdMcNxwt', 'hNdJhpxtMGNlmSVZmSZb', 'OgarOKDltZCewJQnTbGl', 'NjPEwdMvPvURwTXYgRlB', 'vpBCoZQuWcxNmicUyPzv', 'FULHNkNvxDcwlLLnYAZJ', 'GyDiIfHYnPWdvGEtVhhR', 'QZaMucATTIKMaGQDWiMF', 'prOhZeiROgtCXnHaGWSI', 'DnOadsbpYbyTaeZnAuAx', 'LacKToudkichSDIhlmUv', 'pOdJWvhSHkkrrLbDSvey'],
     19                      'Class': [1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1]})
---> 22 setup(data=data,
     23       target='Class',
     24       train_size=0.7,
     25       test_data=None,
     26       ordinal_features=None,
     27       numeric_features=['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9'],
     28       categorical_features=['V10','V11','V12'],
     29       text_features=None,
     30       ignore_features=None,
     31       keep_features=None,
     32       preprocess=True,
     33       imputation_type='simple',
     34       numeric_imputation='mean',
     35       categorical_imputation='constant',
     36       max_encoding_ohe=5,
     37       polynomial_features=True,
     38       polynomial_degree=4,
     39       low_variance_threshold=None,
     40       group_features=None,
     41       group_names=None,
     42       remove_multicollinearity=False,
     43       multicollinearity_threshold=0.9,
     44       bin_numeric_features=None,
     45       remove_outliers=False,
     46       fix_imbalance=True,
     47       fix_imbalance_method=SMOTE(),
     48       transformation=True,
     49       transformation_method='yeo-johnson',
     50       normalize=True,
     51       normalize_method='zscore',
     52       pca=False,
     53       feature_selection=True,
     54       feature_selection_method='classic', 
     55       feature_selection_estimator='lightgbm', 
     56       n_features_to_select=10,
     57       custom_pipeline=None,
     58       custom_pipeline_position=-1,
     59       data_split_shuffle=True,
     60       data_split_stratify=True,
     61       fold_strategy='stratifiedkfold',
     62       fold=10,
     63       fold_shuffle=False,
     64       fold_groups=None,
     65       n_jobs=-1,
     66       use_gpu=True,
     67       html=True,
     68       session_id=123,
     69       log_experiment=True,
     70       system_log=True,
     71       experiment_name='pycaret3_test',
     72       experiment_custom_tags=None,
     73       # engines=None,
     74       verbose=True,
     75       memory=True
     76      )

File ~/.local/lib/python3.8/site-packages/pycaret/classification/functional.py:596, in setup(data, data_func, target, index, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, create_date_columns, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, rare_to_value, rare_value, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, verbose, memory, profile, profile_kwargs)
    594 exp = _EXPERIMENT_CLASS()
    595 set_current_experiment(exp)
--> 596 return exp.setup(
    597     data=data,
    598     data_func=data_func,
    599     target=target,
    600     index=index,
    601     train_size=train_size,
    602     test_data=test_data,
    603     ordinal_features=ordinal_features,
    604     numeric_features=numeric_features,
    605     categorical_features=categorical_features,
    606     date_features=date_features,
    607     text_features=text_features,
    608     ignore_features=ignore_features,
    609     keep_features=keep_features,
    610     preprocess=preprocess,
    611     create_date_columns=create_date_columns,
    612     imputation_type=imputation_type,
    613     numeric_imputation=numeric_imputation,
    614     categorical_imputation=categorical_imputation,
    615     iterative_imputation_iters=iterative_imputation_iters,
    616     numeric_iterative_imputer=numeric_iterative_imputer,
    617     categorical_iterative_imputer=categorical_iterative_imputer,
    618     text_features_method=text_features_method,
    619     max_encoding_ohe=max_encoding_ohe,
    620     encoding_method=encoding_method,
    621     rare_to_value=rare_to_value,
    622     rare_value=rare_value,
    623     polynomial_features=polynomial_features,
    624     polynomial_degree=polynomial_degree,
    625     low_variance_threshold=low_variance_threshold,
    626     group_features=group_features,
    627     group_names=group_names,
    628     remove_multicollinearity=remove_multicollinearity,
    629     multicollinearity_threshold=multicollinearity_threshold,
    630     bin_numeric_features=bin_numeric_features,
    631     remove_outliers=remove_outliers,
    632     outliers_method=outliers_method,
    633     outliers_threshold=outliers_threshold,
    634     fix_imbalance=fix_imbalance,
    635     fix_imbalance_method=fix_imbalance_method,
    636     transformation=transformation,
    637     transformation_method=transformation_method,
    638     normalize=normalize,
    639     normalize_method=normalize_method,
    640     pca=pca,
    641     pca_method=pca_method,
    642     pca_components=pca_components,
    643     feature_selection=feature_selection,
    644     feature_selection_method=feature_selection_method,
    645     feature_selection_estimator=feature_selection_estimator,
    646     n_features_to_select=n_features_to_select,
    647     custom_pipeline=custom_pipeline,
    648     custom_pipeline_position=custom_pipeline_position,
    649     data_split_shuffle=data_split_shuffle,
    650     data_split_stratify=data_split_stratify,
    651     fold_strategy=fold_strategy,
    652     fold=fold,
    653     fold_shuffle=fold_shuffle,
    654     fold_groups=fold_groups,
    655     n_jobs=n_jobs,
    656     use_gpu=use_gpu,
    657     html=html,
    658     session_id=session_id,
    659     system_log=system_log,
    660     log_experiment=log_experiment,
    661     experiment_name=experiment_name,
    662     experiment_custom_tags=experiment_custom_tags,
    663     log_plots=log_plots,
    664     log_profile=log_profile,
    665     log_data=log_data,
    666     verbose=verbose,
    667     memory=memory,
    668     profile=profile,
    669     profile_kwargs=profile_kwargs,
    670 )

File ~/.local/lib/python3.8/site-packages/pycaret/classification/oop.py:727, in ClassificationExperiment.setup(self, data, data_func, target, index, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, create_date_columns, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, rare_to_value, rare_value, polynomial_features, polynomial_degree, low_variance_threshold, group_features, group_names, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, engines, verbose, memory, profile, profile_kwargs)
    724 self.fold_shuffle_param = fold_shuffle
    725 self.fold_groups_param = fold_groups
--> 727 self._initialize_setup(
    728     n_jobs=n_jobs,
    729     use_gpu=use_gpu,
    730     html=html,
    731     session_id=session_id,
    732     system_log=system_log,
    733     log_experiment=log_experiment,
    734     experiment_name=experiment_name,
    735     memory=memory,
    736     verbose=verbose,
    737 )
    739 # Prepare experiment specific params ======================= >>
    741 self.log_plots_param = log_plots

File ~/.local/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py:352, in _TabularExperiment._initialize_setup(self, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, memory, verbose)
    349     cuml_version = cuml_version.split(".")
    350     cuml_version = (int(cuml_version[0]), int(cuml_version[1]))
--> 352 if cuml_version is None or not version.parse(cuml_version) >= version.parse(
    353     "0.15"
    354 ):
    355     message = f"cuML is outdated or not found. Required version is >=0.15, got {__version__}"
    356     if use_gpu == "force":

File /usr/local/envs/Jun_24_2022/lib/python3.8/site-packages/packaging/version.py:49, in parse(version)
     43 """
     44 Parse the given version string and return either a :class:`Version` object
     45 or a :class:`LegacyVersion` object depending on if the given version is
     46 a valid PEP 440 version or a legacy version.
     47 """
     48 try:
---> 49     return Version(version)
     50 except InvalidVersion:
     51     return LegacyVersion(version)

File /usr/local/envs/Jun_24_2022/lib/python3.8/site-packages/packaging/version.py:264, in Version.__init__(self, version)
    261 def __init__(self, version: str) -> None:
    262 
    263     # Validate the version and parse it into pieces
--> 264     match = self._regex.search(version)
    265     if not match:
    266         raise InvalidVersion(f"Invalid version: '{version}'")

TypeError: expected string or bytes-like object
```

### Installed Versions

<details>
System:
    python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)  [GCC 10.3.0]
executable: /usr/local/envs/Jun_24_2022/bin/python3.8
   machine: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.10

PyCaret required dependencies:
                 pip: 22.2.2
          setuptools: 60.10.0
             pycaret: 3.0.0rc3
             IPython: 8.4.0
          ipywidgets: 8.0.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.4.3
              jinja2: 3.1.2
               scipy: 1.8.1
              joblib: 1.1.0
             sklearn: 1.1.2
                pyod: 1.0.4
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.6.0rc1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.10.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: 1.1.0
            pmdarima: 2.0.1
              psutil: 5.9.1

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.2.7
                umap: 0.5.3
    pandas_profiling: 3.2.0
  explainerdashboard: 0.4.0
             autoviz: 0.1.43
           fairlearn: 0.7.0
             xgboost: 2.0.0.dev0
            catboost: 1.0.6
              kmodes: 0.12.1
             mlxtend: 0.20.0
       statsforecast: 1.0.0
        tune_sklearn: 0.4.3
                 ray: 2.0.0
            hyperopt: 0.2.7
              optuna: 3.0.0rc0
               skopt: 0.9.0
              mlflow: 1.28.0
              gradio: 3.1.8b0
             fastapi: 0.80.0
             uvicorn: 0.18.3
              m2cgen: 0.10.0
           evidently: 0.1.56.dev0
                nltk: 3.7
            pyLDAvis: Not installed
              gensim: Not installed
               spacy: Not installed
           wordcloud: 1.8.2.2
            textblob: 0.17.1
               fugue: 0.7.1
           streamlit: Not installed
             prophet: Not installed
            cuml                      22.8.0
</details>

### LINKED ISSUE #2987: [INSTALL]: cuML + pycaret install steps?
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Linux-5.4.0-125-generic-x86_64-with-glibc2.31

### Installation Method

Other

### pycaret Version

2.x + 3.pre

### Python Version

3.9

### Description

I've been trying to get pycaret and cuML (rapids) installed together for a while now, and I think I'm missing something basic.

Main issue seems to be that the Rapids team focus on conda, pycaret uses pip - and this leads to all sorts of package conflicts.

Is there a best practice to get this working?
The rapids team page simply adds pycaret from conda-forge, but this seems to not work either because scipy (and other packages) installed with cuML are far newer than pycaret supports.

I'm going to retry all the different avenues I've attempted so far, and will document the errors and add them as comments
e.g. pip install pycaret; conda install cuML
conda install cuML; pip install pycaret
conda install cuML pycaret
(with the relevant conda repos and cudatoolkit versions included, pycaret --pre or current, etc.)

### Installation Logs

_No response_

### PR DESCRIPTION
**Pull request by beckernick**
This PR resolves the current challenges using cuML with PyCaret by updating the version checking utilities and relaxing the Numba version constraint.

Closes https://github.com/pycaret/pycaret/issues/3075 , closes #2914, closes #2987 , and closes https://github.com/pycaret/pycaret/issues/2710 .

### CODE REVIEW

**Comment by Yard1** [comment]
Hey @beckernick, thanks for doing this. Have you tested it on your end on eg. colab?

**Review by ngupta23 — APPROVED** [review]

**Comment by beckernick** [comment]
> Hey @beckernick, thanks for doing this. Have you tested it on your end on eg. colab?

Yes. I ran through the basic classification and regression workflows in https://pycaret.gitbook.io/docs/get-started/modules on my local workstation (Intel Xeon Gold 6128 CPU + RTX8000 GPU) with both cuML 22.10 and the current 22.12 nightly. I saw GPU utilization as expected for LR, SVC, RF, etc. while the various cuML estimators were shown as active in the `compare_models` table.

If there's a different or more robust, preferred test workflow, happy to run it locally.

**Comment by beckernick** [comment]
> Hey @beckernick, thanks for doing this. Have you tested it on your end on eg. colab?

Yes. I ran through the basic classification and regression workflows in https://pycaret.gitbook.io/docs/get-started/quickstart on my local workstation (Intel Xeon Gold 6128 CPU + RTX8000 GPU) with both cuML 22.10 and the current 22.12 nightly. I saw GPU utilization as expected for LR, SVC, RF, etc. while the various estimators were listed as active in the `compare_models` table [0].

If there's a different or more robust, preferred test workflow, happy to run it locally.

[0]


Initiated | . . . . . . . . . . . . . . . . . . | 22:03:45
-- | -- | --
Status | . . . . . . . . . . . . . . . . . . | Fitting 10 Folds
Estimator | . . . . . . . . . . . . . . . . . . | SVM - Linear Kernel

See "GPU 0" in the nvdashboard jupyterlab widget on the right in this clip (GPU 1 is using my monitor and can be ignored for this purpose):
[pycaret-gpu-activity.webm](https://user-images.githubusercontent.com/8457388/202955819-86dd44d6-0939-4fb2-a94e-489a748a178f.webm)

**Review by Yard1 — APPROVED** [review]
Awesome, thanks for confirming!

**Pull request merged**
