### PR TITLE
Created an enum class for allowed time series plot data types and replaced string usages with TSAllowedPlotDataTypes Enum instances

### LINKED ISSUE #2415: [ENH] Add ENUM for allowed data types instead of strings
Logic looks good, but I think we whouls be using enums for data types and split types instead of regular strings (ofc we should allow the user to pass in a string, but we should use enums in the code). Let me know what you think

_Originally posted by @Yard1 in https://github.com/pycaret/pycaret/pull/2413#pullrequestreview-943761144_

### PR DESCRIPTION
**Pull request by desaizeeshan22**
## 2415

Add ENUM for allowed data types instead of strings #2415

Closes #2415

#### Describe the changes you've made

Created an enum class for allowed time series plot data types and replaced string usages with TSAllowedPlotDataTypes Enum instances

## Type of change
- [x] My code follows the code style of this project.
- [x] Code style update (formatting, local variables)

## How Has This Been Tested?

Used the existing  test_get_data_types_to_plot in the file test_time_series_utils_plots.py

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 image  | <b>image </b> | 
image | <b>image</b>| 
image| <b>image</b>|

### CODE REVIEW

**Comment by ngupta23** [comment]
@desaizeeshan22 Thanks for taking the initiative to add this. Can you comment on the actual Issue so that I can assign it to you?

Also, a few changes - Currently, we are adding change to `develop` branch (this may change in the future to `master` but for now, it is `develop`. I have made the change in this PR, but the tests are failing now. Can you have a look please?

I see you have changed the allowed type to ENUM. Can you check if the plots still work, since the users will be specifying the string values in plot_model and check_stats not the ENUM.

```python
eda.plot_model(data_kwargs={"plot_data_type": ["original", "imputed", "transformed"]) 
```

**Comment by desaizeeshan22** [comment]
Ohh okay I see the plots are failing because the supported types are ENUMS.How do you suggest I go about changing this should I use the ENUM.value instead which outputs a string?

**Comment by ngupta23** [comment]
> Ohh okay I see the plots are failing because the supported types are ENUMS.How do you suggest I go about changing this should I use the ENUM.value instead which outputs a string?

The user should still enter the string (we should not change the user interface). Inside the code, when you check for correctness, you will have to check the strong against the possible ENUM values (currently, it is just checking string against string).

**Comment by desaizeeshan22** [comment]
image

Can you check now ? The plots seemed to be working!

**Comment by ngupta23** [comment]
It seems that the tests are failing. Can you merge the latest develop branch into your branch and then we can evaluate the changes?

**Comment by desaizeeshan22** [comment]
Yup just finished merging the latest changes on develop branch with my branch

**Review by ngupta23 — APPROVED** [review]

**Pull request merged**
