### PR TITLE
added weights as a class variable in supervised experiment

### LINKED ISSUE #3331: [BUG]: Optimize - blend_models - changing weights (ignores the weights)
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

I follow the documentation (https://pycaret.gitbook.io/docs/get-started/functions/optimize) in order to fine tune the weights of a blend and the result ignores the weights. When I check the blend, there are no weights either. 

### Reproducible Example

```python
# load dataset
from pycaret.datasets import get_data
diabetes = get_data('diabetes')

# init setup
from pycaret.classification import *
clf1 = setup(data = diabetes, target = 'Class variable')

# train a few models
lr = create_model('lr')
dt = create_model('dt')
knn = create_model('knn')

# blend models
blender_weighted = blend_models([lr,dt,knn], weights = [0.5,0.2,0.3])

# tune blender
tuned_blender = tune_model(blender_weighted)
```

### Expected Behavior

image

### Actual Results

```python-traceback
VotingClassifier(estimators=[('Logistic Regression',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=1000,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=5243,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('Decision Tree Classifier',
                              DecisionTreeClassifier(ccp_alpha=0....
                                                     min_impurity_decrease=0.0,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     random_state=5243,
                                                     splitter='best')),
                             ('K Neighbors Classifier',
                              KNeighborsClassifier(algorithm='auto',
                                                   leaf_size=30,
                                                   metric='minkowski',
                                                   metric_params=None,
                                                   n_jobs=-1, n_neighbors=5,
                                                   p=2, weights='uniform'))],
                 flatten_transform=True, n_jobs=-1, verbose=False,
                 voting='soft', weights=None)
```

### Installed Versions

<details>
System:
    python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
executable: M:\Working\- ENVS\PyCaret39\Scripts\python.exe
   machine: Windows-10-10.0.19042-SP0

PyCaret required dependencies:
                 pip: 23.0.1
          setuptools: 67.3.3
             pycaret: 3.0.0rc9
             IPython: 7.34.0
          ipywidgets: 7.7.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.8.1
              joblib: 1.2.0
             sklearn: 1.2.1
                pyod: 1.0.2
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.5
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.10.0
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.16.1
               tbats: 1.1.0
            pmdarima: 1.8.5
              psutil: 5.9.1

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.2.7
                umap: 0.5.3
    pandas_profiling: 4.0.0
  explainerdashboard: 0.4.0
             autoviz: 0.1.58
           fairlearn: 0.7.0
             xgboost: 1.7.4
            catboost: 1.0.6
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: 0.4.3
                 ray: 1.13.0
            hyperopt: 0.2.7
              optuna: 3.1.0
               skopt: 0.9.0
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: 0.10.0
           evidently: Not installed
               fugue: Not installed
           streamlit: 1.18.1
             prophet: 1.1.2
</details>

### PR DESCRIPTION
**Pull request by kumar21120**
Made Changes to pycaret/internal/pycaret_experiment/supervised_experiment.py

# Related Issue or bug

Closes #3331

# Describe the changes you've made

Added weights variable in the following piece of code of supervised_experiment.py

```python
 if self._ml_usecase == MLUsecase.CLASSIFICATION:
     model = voting_model_definition.class_def(
         estimators=estimator_list, voting=method, n_jobs=self.gpu_n_jobs_param
         estimators=estimator_list,
         voting=method,
         weights=weights,
         n_jobs=self.gpu_n_jobs_param,
     )
```
# Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I ran the piece of code presented in Issue # 3331, and now it show the weights used instead of None. Before the change,  the voting classifier was giving each classifier the same weight but now it give the weights which is provided by the user because it shows the provided weights when you print the model.  

# Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

NA

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by ngupta23** [comment]
@kumar21120 Thanks for contributing to the project!

- Could you check why the code quality checks are failing? 
- Also, it shows that you have updated 27 files. Could you only commit the files on which you have made a code change?

Thanks!

**Comment by kumar21120** [comment]
@ngupta23 Thank you for reviewing the pull request. 

I will check why the code quality is failing? As per the contributing document, I did 'isort pycaret' and 'black pycaret'.

Regarding the number of files, I made changes to supervised_experiment.py and to the gitignore file to ignore the '.DS_Store'.

All the other files were modified because when I did 'isort pycaret' and 'black pycaret'.

This is my first time contributing here. Please let me know if I am missing anything.

Also, should I close this pull request and start a new one?

**Comment by Yard1** [comment]
@kumar21120 Please make sure you are using `black==22.12.0`

**Comment by kumar21120** [comment]
Thank you @Yard1. I will try it.

**Pull request closed without merging**
