### PR TITLE
Refactor compare_models()

### PR DESCRIPTION
**Pull request by Yard1**
Refactors `compare_models()` in classification and regression modules in order to:
* Use `create_models()` internally, with **unchanged** display (required modification of create_models(), however default functionality is unchanged)
* Accept completed models to be compared with `estimator_list` parameter - it is possible to now run code such as:
```python
top3 = compare_models(n_select=3)
top3_tuned = [tune_model(x) for x in top3)
compare_models(estimator_list=top3+top3_tuned) # will create a score grid of passed models, allowing for easy comparison of untuned and tuned ones. Also works with ensembled and blended models, though stacked models are currently unsupported
```
image (the index is on purpose, as it is the same as the index of elements in the passed list)
* Cut down on the code, general cleanup of some parts

This will allow maintenance to be much easier, as `compare_models()` will not need to be edited aside from adding some names to dicts (which should be global, to be honest). As a side effect, `compare_models()` is now faster, as it doesn't need to recreate models again for saving best. Later, I would like to add an option to compare models with train set instead of CV.

Also made it so that `create_models()` shows the TT in score grid (so that it can be shown in `compare_models()`. Could probably be extended to other functions.

References https://github.com/pycaret/pycaret/issues/358

### CODE REVIEW

**Comment by Yard1** [comment]
@pycaret Could you take a look? I think that this is a very good and helpful change. I'm more of a software engineer than data scientist, so such kind of changes are up my alley.

**Comment by pycaret** [comment]
@Yard1 Thanks for doing that. I am in 100% agreement that the code requires some deep cleaning. I am not a software engineer so I am guilty of writing code that is not the most optimal. However, there are couple of things I want to do before taking on these major changes. In following order:

- Adopt to Stacking Classifier instead of in-house function in stack_models
- Remove create_stacknet in PyCaret 2.1 (already committed)
- Change behavior of save_model, instead of returning list. Model object should be appended in sklearn.pipeline so that we can use it for pmml conversion. The reason it is like that is because of stack_models and create_stacknet function.
- Some other minor bug fix
- Convert repository from private to organization
- Add colloborators / members into the project (like yourself) 
- Develop processes and add reviewers in place to implement governance process.

I expect to do all this in next couple of weeks. Once I have a good start on these items we can either colloborate on how to take on the changes you have submitted through PR.

In the mean time, can you submit a separate PR for the part where you have refactored code in setup function to avoid multiple if and else. I can merge that PR sooner.

**Comment by Yard1** [comment]
That works for me. The fact changing the way stacked models work is planned is why I didn't bother to add support for them. I will open up a new PR with some general code cleanup that doesn't change any functionality.

**Comment by Yard1** [comment]
I'm closing this for now as the functionality in this PR will be introduced during the planned general refactor.

**Pull request closed without merging**
