### PR TITLE
Update Regression Tutorial Level Beginner - REG101.ipynb

### PR DESCRIPTION
**Pull request by simoneperazzoli**
Updating description: replacing final_knn by final_lightgbm

### CODE REVIEW

**Comment by pycaret** [comment]
@simoneperazzoli Thanks for submitting this. Really under next release PR's. Will keep it open for a while and review as soon as I get chance.

**Comment by simoneperazzoli** [comment]
> @simoneperazzoli Thanks for submitting this. Really under next release PR's. Will keep it open for a while and review as soon as I get chance.

Thank you for the feedback.

**Comment by simoneperazzoli** [comment]
@pycaret , please, could you consider my regression example too in this PR? Thank you in advance.

**Comment by pycaret** [comment]
@simoneperazzoli Thanks. Merged now.

**Pull request merged**
