### PR TITLE
Addition of MCC as classification metric

### PR DESCRIPTION
**Pull request by dataprofessor**
I would like to propose the addition of MCC as classification metric.

### CODE REVIEW

**Comment by TechyNilesh** [comment]
I would like to propose the addition of Sensitivity and specificity as classification metric.

**Comment by TechyNilesh** [comment]
I try NLP but Voc size is showing ZERO why

**Comment by reza1615** [comment]
> I would like to propose the addition of MCC as classification metric.

Also I sent a pull request to add MCC to the training scores

**Comment by pycaret** [comment]
Merged to branch dev-1.0.1. 

Merge to master not required. Closing this.

**Pull request closed without merging**
