### PR TITLE
Comet Compare Logging Bug Fix

### PR DESCRIPTION
**Pull request by sherpan**
# Related Issue or bug

The logger was logging a df as a metric which was throwing an error in Comet

# Describe the changes you've made
Changed the logging of a metric to a logging of a dataframe
# Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

[Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://www.comet.com/sherpan/caret-debug-2?shareable=FfD2J4uJ6mFI7QgGQVP1icL7O

# Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)

N/A

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]

**Comment by Yard1** [comment]
Thanks!

**Comment by sherpan** [comment]
thanks @Yard1! Just curious as to when you guys are planning to do another pypi release? Want to create a tutorial of pycaret and comet and would love for the changes i pushed to be reflected after i run `pip install pycaret`

**Comment by Yard1** [comment]
@sherpan We'll probably release a patch in a week or so!

**Comment by sherpan** [comment]
@Yard1 any update on the patch release?

**Pull request merged**
