### PR TITLE
Added support for alphanumeric frequencies

### PR DESCRIPTION
**Pull request by sayantan1410**
#### Info about the issue 
Add code that supports frequencies like '10T'. Currently it is only handling frequency that are member of the class Season_Period. 
#### Changes made  
Added code that detects frequencies that has both number and alphabets in it. Then returns the seasonal_period according to it. 
For example, 
'10T' will be returned as 10*60 = 600 

#### Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by ngupta23** [comment]
Hi @sayantan1410 , Can you add unit tests for these conditions? Let me know if you need help to understand how to do that. Thanks!

**Comment by sayantan1410** [comment]
Yes, I will need a little bit of help to understand how to do that !! @ngupta23

**Comment by sayantan1410** [comment]
Hello, I have pushed the changes @ngupta23 
Let me know if everything is alright, I have made a merge commit in the end as my branch was behind by 3 commits, hope that is not a problem.

**Review by ngupta23 — APPROVED** [review]

**Comment by ngupta23** [comment]
Looks good @sayantan1410 . Thank you for your first contribution to pycaret!

**Pull request merged**
