### PR TITLE
Contributing development setup instructions. Simplify CI test pipelines

### PR DESCRIPTION
**Pull request by khrapovs**
#### Describe the changes you've made

I wanted to contribute, but could not find a clear instruction on how to setup a development environment and run tests. So, I wrote down the steps I followed and that would be helpful to other new contributors.

In addition, I simplified CI test pipeline. Most likely I miss some context that forced the pipeline to be more complicated than necessary and I would be glad to reflect it in the docs. In particular:
- Windows and Ubuntu pipelines were testing for different python versions. Now it is 3.6-9.
- Testing plots was separated from all other tests. It seems they are running just fine together with all other tests.
- A couple of test functions were simply deleted before testing! Now this behavior is achieved with decorator `@pytest.mark.skip`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by moezali1** [comment]
@Yard1 @tvdboom FYA

**Comment by moezali1** [comment]
@khrapovs This is amazing. Tagged relevant people to review the PR. 

Thanks for your contributions.

**Comment by Yard1** [comment]
Hey @khrapovs, thanks for your contribution. The reason for `test_plots` being separate is to speed up the CI pipeline as it can be ran in parallel with other tests. There was an issue with Python 3.9 on windows, which led us to excluding it from the pipeline - we have already removed 3.6 tests on a different branch. Hope that provides some context.

The documentation changes look excellent, thank you for that!

**Comment by khrapovs** [comment]
@Yard1 @moezali1 Thanks for the quick feedback!

CI speed. Plot tests run ~5 minutes. All other tests ~15 minutes. All these numbers are already very big, and I still do not understand why single out plots? If you really want to speed up the tests, why not using https://pypi.org/project/pytest-parallel/? I do not know exactly why machines are running Github actions, but normally these days 4 threads is more or less standard. So, I would expect at least 2x and at best 4x speedup. Should I try it with pycaret? Would you be against a new dependency for tests?

Looks like 3.9 is totally fine on Windows again... ;)

Should I remove 3.6 in this PR?

**Comment by Yard1** [comment]
Awesome to see 3.9 working on windows - it was some sort of a pypi issue then, glad to see it fixed. Yeah, we are going to drop support for 3.6 in a next release, following our dependencies, so it makes sense to stop testing for it. I'd like to ask you to keep the plot tests as they were, though - we cannot easily use pytest parallel due to limited memory on github runners. Having them run in a separate job works better.

**Comment by khrapovs** [comment]
@Yard1 Sure, as you prefer. I added back test_plots pipeline and the removal step in the "main" test pipeline. But I also added the matrix of python versions to make plot tests really correspond to all others. Let me know if I should leave only 3.8 as at was before.

**Comment by khrapovs** [comment]
@Yard1 @tvdboom Any news here?

**Review by Yard1 — APPROVED** [review]
Looks good, thanks!

**Review by ngupta23 — COMMENTED** [review]
@khrapovs @Yard1 Do we have precommit hooks? The instructions are pointing to it, but I am not sure if this is setup already.

If not, it would be nice to do this as it will ensure consistency.

**Comment by khrapovs** [comment]
@ngupta23 I am a bit surprised by your comment. This file `.pre-commit-config.yaml` is clearly in the root of the repo ;)

**Comment by ngupta23** [comment]
@khrapovs The PRs are not blocked if the pre-commit fails as far as I understand it. Is this something that should be enforced? I remember when I contributed to `sktime`, this was strictly enforced in the PRs but this was a while back.

Plus other hooks can be added as well similar to `sktime`: https://github.com/alan-turing-institute/sktime/blob/main/.pre-commit-config.yaml

@Yard1 Do you have any thoughts about the enforcement?

**Pull request merged**
