### PR TITLE
Support scikit-learn 1.5

### PR DESCRIPTION
**Pull request by celestinoxp**
Add support to scikit-learn 1.5

[main highlights]
 - Pandas: now minimum version of pandas is 2.2.x, with a lot of bugfixes and new funcs like engine=numba to have performance gains with big datasets. See https://pandas.pydata.org/docs/whatsnew/v2.2.0.html
 - Sktime: Updated to latest version.

[others]
Closes https://github.com/pycaret/pycaret/issues/4017
Closes https://github.com/pycaret/pycaret/issues/4013

### CODE REVIEW

**Review by Yard1 — APPROVED** [review]
Thanks for the hard work!

**Comment by xabieza** [comment]
sorry, where is the code to fix the error? thx

**Comment by MinuraPunchihewa** [comment]
Hey @celestinoxp, @Yard1,
I just wanted to know if the above changes have been released? I did not see it mentioned in any of the release notes. In what version can this expected to be available? Further, I noticed that the README states that PyCaret 3.4 is available, however, I do not see it in PyPI.

**Comment by MinuraPunchihewa** [comment]
@celestinoxp Thanks for letting me know, @celestinoxp.

**Pull request merged**
