### PR TITLE
Address issue #2423

### PR DESCRIPTION
**Pull request by NeptuneN**
## Related Issuse or bug

Implements #2423 

#### Describe the changes you've made

Removed references of this code line in two files (tabular.py, utils.py):
```python
from pycaret.internal.validation import *
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Ran unit tests locally using pytest 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by ngupta23** [comment]
Well it is not that simple. You need to add the imports explicitly depending on what is being used in the module. Just removing it will break things.

Plus, I think there are about 6 or 7 different places where this needs to be changed. 

Also, if you are doing this, please create a branch out of `time_series` and merge it back there instead of `master`.

Thanks!

**Comment by ngupta23** [comment]
Well it is not that simple. You need to add the imports explicitly depending on what is being used in the module. Just removing it will break things.

Plus, I think there are about 6 or 7 different places where this needs to be changed. 

Also, if you are doing this, please create a branch out of `time_series` and merge it back there instead of `master`.

Thanks!

**Comment by ngupta23** [comment]
@NeptuneN As you can see the tests are failing since the removal of the statement is not substituted with the correct explicit imports from the validation module.

**Comment by NeptuneN** [comment]
Right, I noticed that, my bad. I had a gut feeling that the Issue felt a little too simple, so I wasn't too sure.

Not to mention that I was on the wrong branch. Since I also had to change my own working branch locally, not seeing an option to change it when editing the pull request, should I just make a new pull request and close this one? @ngupta23

**Comment by ngupta23** [comment]
> Not to mention that I was on the wrong branch. Since I also had to change my own working branch locally, not seeing an option to change it when editing the pull request, should I just make a new pull request and close this one? @ngupta23

Thank you for picking this up. Yes, you can close this one and resubmit to the right branch. 

FYI.. I like what your professor is doing. If I understood it correctly, you are being asked to make a PR to an open source project of your choice - correct me if I am wrong.

Just an piece of advice. Before making a PR, it is often advisable to discuss it in the issue itself and sign up for it to be assigned to you. This way, a lot of the finer details (which may not be captured in the Issue) can be clarified before the work actually starts :).

**Comment by NeptuneN** [comment]
Thank you for the advice! I'll keep it in mind for the future. :D

**Comment by ngupta23** [comment]
@NeptuneN Do you mind leaving a comment on the Issue so I can officially assign this to you :).

**Pull request closed without merging**
